### ISSUE TITLE
Mobile users - elastic search problem

### ISSUE THREAD

**Issue by philipkaare** [dimagi/commcare-hq#10016]
I managed to get most of CommcareHQ up and running, however there still seems to be some issues with Elasticsearch with regards to mobile users. When I create a mobile user everything seems to be going fine, I can see in the log output that ES is contacted and the update is saved, however when I try to update the page it says there are no mobile users and inspecting the network traffic just shows an empty JSON return. I suspect this issue is also related to the inability of the Commcare ODK app to log in to the system. 

My setup runs in Docker with this [dockerfile](https://github.com/philipkaare/commcare-
hq/blob/master/Dockerfile) and this [setup script](https://github.com/philipkaare/commcare-hq/blob/master/docker/docker-run.sh). 

I do not get any error messages connected to this issue. 

I would really appreciate some pointers on how to debug/investigate this issue. Thanks!

**Comment by czue** [comment]
Are you seeing the users in the elasticsearch index? Easiest way to test is by using something like elasticsearch head: https://mobz.github.io/elasticsearch-head/

**Comment by czue** [comment]
also you may want to check out @snopoke's latest changes to improve our docker setup: https://github.com/dimagi/commcare-hq/pull/10018

**Comment by philipkaare** [comment]
Thanks for the suggestion. With ES-head I do see the user, however something strange is going on I think: 

This is the user: http://pastebin.com/m3nZvq2f
At the same time it says that cluster health is yellow (35 out of 40) and I see this: [screenshothttp](http://imgur.com/OQAHfmL)

Any idea what might be going on?

**Comment by benrudolph** [comment]
you may need to run `./manage.py ptop_es_manage --flip_all_aliases` though not clear that that's the issue since the worker is being inserted properly into elastic

**Comment by philipkaare** [comment]
Okay, I did that. It led to a cluster health of 45 out of 50, but with no improvement in the number of users shown :S . 

I'll have a look at your updated docker scripts Monday. I see one difference in the way you set up PostgreSQL, I am using the latest, whereas you use a certain (earlier?) version. Do you think this could explain the problem?

**Comment by benrudolph** [comment]
i doubt it's related to postgres. especially since you're seeing the user in ElasticSearch correct?

**Comment by philipkaare** [comment]
Yes, I am. I was just thinking that a wrong version of postgres could somehow cause trouble with migrations.

**Comment by philipkaare** [comment]
Okay, so this is still an issue for me, however I now have an error message :) 

`2016-02-10 15:01:27,605 ERROR Internal Server Error: /a/demo/settings/users/web/
Traceback (most recent call last):
  File "/vendor/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vendor/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/corehq/apps/style/decorators.py", line 23, in _wrapped
    return view_func(class_based_view, request, *args, **kwargs)
  File "/mnt/corehq/apps/style/decorators.py", line 76, in _wrapped
    return view_func(class_based_view, request, *args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/mnt/corehq/apps/domain/decorators.py", line 83, in _inner
    return view_func(req, domain_name, *args, **kwargs)
  File "/mnt/corehq/apps/users/decorators.py", line 21, in _inner
    return view_func(request, domain, *args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/mnt/corehq/apps/users/views/__init__.py", line 395, in dispatch
    return super(ListWebUsersView, self).dispatch(request, *args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/mnt/corehq/apps/domain/decorators.py", line 83, in _inner
    return view_func(req, domain_name, *args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/mnt/corehq/apps/domain/views.py", line 195, in dispatch
    return super(LoginAndDomainMixin, self).dispatch(*args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/djangular/views/mixins.py", line 105, in post
    return self.json_response(response_data)
  File "/vendor/lib/python2.7/site-packages/djangular/views/mixins.py", line 43, in json_response
    out_data = json.dumps(response_data, cls=self.json_encoder, **kwargs)
  File "/usr/local/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/vendor/lib/python2.7/site-packages/django/core/serializers/json.py", line 109, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: RequestError(400, u'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][0]: SearchParseException[[hqusers_2016-01-20_1610][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"sort": {"username.exact": "asc"}, "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term": {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type": "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active": true}}]}, "query": {"match_all": {}}}}}]]]; nested: SearchParseException[[hqusers_2016-01-20_1610][0]: from[-1],size[-1]: Parse Failure [No mapping found for [username.exact] in order to sort on]]; }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][1]: SearchParseException[[hqusers_2016-01-20_1610][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"sort": {"username.exact": "asc"}, "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term": {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type": "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active": true}}]}, "query": {"match_all": {}}}}}]]]; nested: SearchParseException[[hqusers_2016-01-20_1610][1]: from[-1],size[-1]: Parse Failure [No mapping found for [username.exact] in order to sort on]]; }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][2]: SearchParseException[[hqusers_2016-01-20_1610][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"sort": {"username.exact": "asc"}, "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term": {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type": "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active": true}}]}, "query": {"match_all": {}}}}}]]]; nested: SearchParseException[[hqusers_2016-01-20_1610][2]: from[-1],size[-1]: Parse Failure [No mapping found for [username.exact] in order to sort on]]; }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][3]: SearchParseException[[hqusers_2016-01-20_1610][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"sort": {"username.exact": "asc"}, "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term": {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type": "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active": true}}]}, "query": {"match_all": {}}}}}]]]; nested: SearchParseException[[hqusers_2016-01-20_1610][3]: from[-1],size[-1]: Parse Failure [No mapping found for [username.exact] in order to sort on]]; }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][4]: SearchParseException[[hqusers_2016-01-20_1610][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"sort": {"username.exact": "asc"}, "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term": {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type": "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active": true}}]}, "query": {"match_all": {}}}}}]]]; nested: SearchParseException[[hqusers_2016-01-20_1610][4]: from[-1],size[-1]: Parse Failure [No mapping found for [username.exact] in order to sort on]]; }]', {u'status': 400, u'error': u'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][0]: SearchParseException[[hqusers_2016-01-20_1610][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"sort": {"username.exact": "asc"}, "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term": {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type": "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active": true}}]}, "query": {"match_all": {}}}}}]]]; nested: SearchParseException[[hqusers_2016-01-20_1610][0]: from[-1],size[-1]: Parse Failure [No mapping found for [username.exact] in order to sort on]]; }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][1]: SearchParseException[[hqusers_2016-01-20_1610][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"sort": {"username.exact": "asc"}, "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term": {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type": "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active": true}}]}, "query": {"match_all": {}}}}}]]]; nested: SearchParseException[[hqusers_2016-01-20_1610][1]: from[-1],size[-1]: Parse Failure [No mapping found for [username.exact] in order to sort on]]; }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][2]: SearchParseException[[hqusers_2016-01-20_1610][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"sort": {"username.exact": "asc"}, "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term": {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type": "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active": true}}]}, "query": {"match_all": {}}}}}]]]; nested: SearchParseException[[hqusers_2016-01-20_1610][2]: from[-1],size[-1]: Parse Failure [No mapping found for [username.exact] in order to sort on]]; }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][3]: SearchParseException[[hqusers_2016-01-20_1610][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"sort": {"username.exact": "asc"}, "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term": {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type": "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active": true}}]}, "query": {"match_all": {}}}}}]]]; nested: SearchParseException[[hqusers_2016-01-20_1610][3]: from[-1],size[-1]: Parse Failure [No mapping found for [username.exact] in order to sort on]]; }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][4]: SearchParseException[[hqusers_2016-01-20_1610][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"sort": {"username.exact": "asc"}, "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term": {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type": "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active": true}}]}, "query": {"match_all": {}}}}}]]]; nested: SearchParseException[[hqusers_2016-01-20_1610][4]: from[-1],size[-1]: Parse Failure [No mapping found for [username.exact] in order to sort on]]; }]'}) is not JSON serializable
`

This came from just running the latest version of Commcare with the official docker script.

**Comment by snopoke** [comment]
try `./manage.py ptop_preindex --replace` which will rebuild all the ES
indexes

On 10 February 2016 at 17:11, philipkaare <notifications@github.com> wrote:

> Okay, so this is still an issue for me, however I now have an error
> message :)
>
> 2016-02-10 15:01:27,605 ERROR Internal Server Error:
> /a/demo/settings/users/web/
> Traceback (most recent call last):
> File "/vendor/lib/python2.7/site-packages/django/core/handlers/base.py",
> line 111, in get_response
> response = wrapped_callback(request, *callback_args, **callback_kwargs)
> File "/vendor/lib/python2.7/site-packages/django/views/generic/base.py",
> line 69, in view
> return self.dispatch(request, *args, **kwargs)
> File "/mnt/corehq/apps/style/decorators.py", line 23, in _wrapped
> return view_func(class_based_view, request, *args, **kwargs)
> File "/mnt/corehq/apps/style/decorators.py", line 76, in _wrapped
> return view_func(class_based_view, request, *args, **kwargs)
> File "/vendor/lib/python2.7/site-packages/django/utils/decorators.py",
> line 29, in _wrapper
> return bound_func(*args, **kwargs)
> File "/mnt/corehq/apps/domain/decorators.py", line 83, in _inner
> return view_func(req, domain_name, *args, **kwargs)
> File "/mnt/corehq/apps/users/decorators.py", line 21, in _inner
> return view_func(request, domain, *args, **kwargs)
> File "/vendor/lib/python2.7/site-packages/django/utils/decorators.py",
> line 25, in bound_func
> return func.__get__(self, type(self))(*args2, **kwargs2)
> File "/mnt/corehq/apps/users/views/__init__.py", line 395, in dispatch
> return super(ListWebUsersView, self).dispatch(request, *args, **kwargs)
> File "/vendor/lib/python2.7/site-packages/django/utils/decorators.py",
> line 29, in _wrapper
> return bound_func(*args, **kwargs)
> File "/mnt/corehq/apps/domain/decorators.py", line 83, in _inner
> return view_func(req, domain_name, *args, **kwargs)
> File "/vendor/lib/python2.7/site-packages/django/utils/decorators.py",
> line 25, in bound_func
> return func.__get__(self, type(self))(*args2, **kwargs2)
> File "/mnt/corehq/apps/domain/views.py", line 195, in dispatch
> return super(LoginAndDomainMixin, self).dispatch(*args, **kwargs)
> File "/vendor/lib/python2.7/site-packages/django/views/generic/base.py",
> line 87, in dispatch
> return handler(request, *args, **kwargs)
> File "/vendor/lib/python2.7/site-packages/djangular/views/mixins.py", line
> 105, in post
> return self.json_response(response_data)
> File "/vendor/lib/python2.7/site-packages/djangular/views/mixins.py", line
> 43, in json_response
> out_data = json.dumps(response_data, cls=self.json_encoder, **kwargs)
> File "/usr/local/lib/python2.7/json/__init__.py", line 251, in dumps
> sort_keys=sort_keys, **kw).encode(obj)
> File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
> chunks = self.iterencode(o, _one_shot=True)
> File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
> return _iterencode(o, 0)
> File
> "/vendor/lib/python2.7/site-packages/django/core/serializers/json.py", line
> 109, in default
> return super(DjangoJSONEncoder, self).default(o)
> File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
> raise TypeError(repr(o) + " is not JSON serializable")
> TypeError: RequestError(400, u'SearchPhaseExecutionException[Failed to
> execute phase [query], all shards failed; shardFailures
> {[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][0]:
> SearchParseException[[hqusers_2016-01-20_1610][0]: from[-1],size[-1]: Parse
> Failure [Failed to parse source [{"sort": {"username.exact": "asc"},
> "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term":
> {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type":
> "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active":
> true}}]}, "query": {"match_all": {}}}}}]]]; nested:
> SearchParseException[[hqusers_2016-01-20_1610][0]: from[-1],size[-1]: Parse
> Failure [No mapping found for [username.exact] in order to sort on]];
> }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][1]:
> SearchParseException[[hqusers_2016-01-20_1610][1]: from[-1],size[-1]: Parse
> Failure [Failed to parse source [{"sort": {"username.exact": "asc"},
> "size": 10, "from": 0, "query": {"filtered": {"fil ter": {" and": [{"term":
> {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type":
> "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active":
> true}}]}, "query": {"match_all": {}}}}}]]]; nested:
> SearchParseException[[hqusers_2016-01-20_1610][1]: from[-1],size[-1]: Parse
> Failure [No mapping found for [username.exact] in order to sort on]];
> }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][2]:
> SearchParseException[[hqusers_2016-01-20_1610][2]: from[-1],size[-1]: Parse
> Failure [Failed to parse source [{"sort": {"username.exact": "asc"},
> "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term":
> {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type":
> "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active":
> true}}]}, "query": {"match_all": {}}}}}]]]; nested:
> SearchParseException[[hqusers_2016-01-20_1610][2]: from[-1],size[-1]: Parse
> Failure [No mapping found for [username.exact] in order to sort on]];
> }{[Yc3fT9d4Q56gP2YTNVf IiQ][hqu sers_2016-01-20_1610][3]:
> SearchParseException[[hqusers_2016-01-20_1610][3]: from[-1],size[-1]: Parse
> Failure [Failed to parse source [{"sort": {"username.exact": "asc"},
> "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term":
> {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type":
> "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active":
> true}}]}, "query": {"match_all": {}}}}}]]]; nested:
> SearchParseException[[hqusers_2016-01-20_1610][3]: from[-1],size[-1]: Parse
> Failure [No mapping found for [username.exact] in order to sort on]];
> }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][4]:
> SearchParseException[[hqusers_2016-01-20_1610][4]: from[-1],size[-1]: Parse
> Failure [Failed to parse source [{"sort": {"username.exact": "asc"},
> "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term":
> {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type":
> "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_ active":
> true}}]}, "query": {"match_all": {}}}}}]]]; nested:
> SearchParseException[[hqusers_2016-01-20_1610][4]: from[-1],size[-1]: Parse
> Failure [No mapping found for [username.exact] in order to sort on]]; }]',
> {u'status': 400, u'error': u'SearchPhaseExecutionException[Failed to
> execute phase [query], all shards failed; shardFailures
> {[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][0]:
> SearchParseException[[hqusers_2016-01-20_1610][0]: from[-1],size[-1]: Parse
> Failure [Failed to parse source [{"sort": {"username.exact": "asc"},
> "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term":
> {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type":
> "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active":
> true}}]}, "query": {"match_all": {}}}}}]]]; nested:
> SearchParseException[[hqusers_2016-01-20_1610][0]: from[-1],size[-1]: Parse
> Failure [No mapping found for [username.exact] in order to sort on]];
> }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_16 10][1]:
> SearchParseException[[hqusers_2016-01-20_1610][1]: from[-1],size[-1]: Parse
> Failure [Failed to parse source [{"sort": {"username.exact": "asc"},
> "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term":
> {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type":
> "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active":
> true}}]}, "query": {"match_all": {}}}}}]]]; nested:
> SearchParseException[[hqusers_2016-01-20_1610][1]: from[-1],size[-1]: Parse
> Failure [No mapping found for [username.exact] in order to sort on]];
> }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][2]:
> SearchParseException[[hqusers_2016-01-20_1610][2]: from[-1],size[-1]: Parse
> Failure [Failed to parse source [{"sort": {"username.exact": "asc"},
> "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term":
> {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type":
> "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active":
> true}}]}, "query" : {"matc h_all": {}}}}}]]]; nested:
> SearchParseException[[hqusers_2016-01-20_1610][2]: from[-1],size[-1]: Parse
> Failure [No mapping found for [username.exact] in order to sort on]];
> }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][3]:
> SearchParseException[[hqusers_2016-01-20_1610][3]: from[-1],size[-1]: Parse
> Failure [Failed to parse source [{"sort": {"username.exact": "asc"},
> "size": 10, "from": 0, "query": {"filtered": {"filter": {"and": [{"term":
> {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type":
> "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active":
> true}}]}, "query": {"match_all": {}}}}}]]]; nested:
> SearchParseException[[hqusers_2016-01-20_1610][3]: from[-1],size[-1]: Parse
> Failure [No mapping found for [username.exact] in order to sort on]];
> }{[Yc3fT9d4Q56gP2YTNVfIiQ][hqusers_2016-01-20_1610][4]:
> SearchParseException[[hqusers_2016-01-20_1610][4]: from[-1],size[-1]: Parse
> Failure [Failed to parse source [{"sort": {"username.exact": "asc"}, "s
> ize": 10 , "from": 0, "query": {"filtered": {"filter": {"and": [{"term":
> {"user.domain_memberships.domain": "demo"}}, {"term": {"doc_type":
> "WebUser"}}, {"term": {"base_doc": "couchuser"}}, {"term": {"is_active":
> true}}]}, "query": {"match_all": {}}}}}]]]; nested:
> SearchParseException[[hqusers_2016-01-20_1610][4]: from[-1],size[-1]: Parse
> Failure [No mapping found for [username.exact] in order to sort on]]; }]'})
> is not JSON serializable
>
> This came from just running the latest version of Commcare with the
> official docker script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/issues/10016#issuecomment-182417153>
> .
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by philipkaare** [comment]
@snopoke It fixed it. Thanks so much, this issue has been plaguing me for some time as you know :)
