### ISSUE TITLE
Allow for CommCare builds that aren't J2ME enabled

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcare-hq#12347]
**Mindset**: Do as little as possible to support the j2me app building experience. Instead, act like everyone uses Android but make it still just barely possible to use J2ME. (Ok I’m exaggerating for effect, but don’t break our back adding features just to make the j2me app building experience nice.)

**Background**: There are two ways that a build can get added to CommCare HQ.
1. The mobile build process (Jenkins) makes a POST request to HQ with 3 elements: j2me jad/jar artifacts as a zip, a version name, and a build number. The build number is used to know when to overwrite existing artifacts with incoming ones. This is used on www.commcarehq.org.
2. You can manually add a build using the 'import a new build from the build server' UI at [this page](https://www.commcarehq.org/builds/edit_menu/). This is how we add builds to staging.commcarehq.org and local dev environments, which aren't hooked up to Jenkins.

**Have HQ detect J2ME eligibility** by whether or not the build has the right attachments and save that to `j2me_enabled` (which defaults to true for backwards compatibility).
- the new `j2me_enabled` property will go on [CommCareBuild](https://github.com/dimagi/commcare-hq/blob/5509bc6625965d2c4b0a82b9a2abbe2c233bdee2/corehq/apps/builds/models.py#L24-24)
- The `j2me_enabled` value will be inferred from whether or not the j2me jad/jar artifacts zip is present. This is the file attachment in the POST which has previously always been present.
  - if no zip attachment is provided in [`builds.views.post`](https://github.com/dimagi/commcare-hq/blob/5509bc6625965d2c4b0a82b9a2abbe2c233bdee2/corehq/apps/builds/views.py#L34-L36), the current behavior is to reject the HTTP request. Instead, set `j2me_enabled` to `False`.
  - if an artifacts zip is provided, the current behavior is to make a build using the [`CommCareBuild.create_from_zip`](https://github.com/dimagi/commcare-hq/blob/5509bc6625965d2c4b0a82b9a2abbe2c233bdee2/corehq/apps/builds/models.py#L74-74) method, and this should remain unchanged.
- modify the manual import UI (at the bottom of [the build menu UI](https://www.commcarehq.org/builds/edit_menu/)) to set `j2me_enabled` to `False` if an artifacts URL isn't provided. Corresponds to the [`import_build`](https://github.com/dimagi/commcare-hq/blob/5509bc6625965d2c4b0a82b9a2abbe2c233bdee2/corehq/apps/builds/views.py#L115) method. Add some text to the UI mentioning this behavior. (This is the same idea as above; zip file missing == `j2me_enabled` is `False`.)

**Include a J2ME Enabled column** in [the build menu UI](https://www.commcarehq.org/builds/edit_menu/); a simple column that contains a checkmark icon if the build is j2me-enabled and is blank otherwise. This is for debugging purposes and to potentially reduce support burden of any confusion that arises from the split.
- You can add the column just to the right of the **Superuser Only** column:
  <img width="1193" alt="screen shot 2016-07-07 at 4 00 17 pm" src="https://cloud.githubusercontent.com/assets/137212/16667727/f5186dac-445b-11e6-8f03-b8610037cafd.png">
-  Here's the [template to edit](https://github.com/dimagi/commcare-hq/blob/ac5419d5277111d1751a5e2b386624a533c71b6c/corehq/apps/builds/templates/builds/edit_menu.html#L142-142)

**Disable J2ME download if the selected CommCare version is ineligible**, and add a link with instructions for building for J2ME.
- Replace the body of this collapsable with a message about why it can't be downloaded and a link to a help-site page that explains what to do (including the last released J2ME version).
  <img width="1035" alt="screen shot 2016-07-07 at 4 04 06 pm" src="https://cloud.githubusercontent.com/assets/137212/16667918/ba5d5f6e-445c-11e6-94ef-039343218d84.png">
- The "CommCare Version" we're talking about is the "CommCare Version" setting on this page:
  <img width="947" alt="screen shot 2016-07-07 at 4 06 37 pm" src="https://cloud.githubusercontent.com/assets/137212/16667956/e7d265c0-445c-11e6-8958-de4ebc103616.png">
- It can be looked up by checking `app.build_spec` which is a `BuildSpec`, which you can call `get_build` on to get a `CommCareBuild`, from which you can check the `j2me_enabled` property that you'll be adding
  - there's a shortcut for that which is `app.get_build`
  - you may want to consider caching `j2me_enabled` value lookup by `build_version`, as adding one couchdb call per app release on the deploy page seems like an unwelcome burden. Caching the full list of supported j2me versions that appear in the build menu is another option, as that list will never be longer than a few dozen and is fine to retrieve from that cache all at once.

**Comment by czue** [comment]
@dannyroberts pretty sure we can close this, yeah? do we even support j2me anymore?

**Comment by dannyroberts** [comment]
Yeah I mean I think the point of this was to figure out how to smooth the path to _not_ supporting J2ME. Looks like Manish implemented this or a chunk of it, and regardless at this point I agree leaving it open isn't providing us any value. (I for one had totally forgotten about it.)
