### ISSUE TITLE
Installation issue - Django

### ISSUE THREAD

**Issue by SkylerGatibaru** [dimagi/commcare-hq#16416]
Im setting up the Commcare-hq production server & when im setting the Django environment, i come across this::

`Traceback (most recent call last):
  File "./manage.py", line 114, in <module>
    patch_jsonfield()
  File "./manage.py", line 74, in patch_jsonfield
    from django.core.exceptions import ValidationError
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named django.core.exceptions`

I'm new to Django and python. Kindly, anyone, help me with

**Comment by emord** [comment]
> ImportError: No module named django.core.exceptions

It appears that you don't have django installed. To install you can use `pip install -r requirements/requirements.txt` as documented in the readme https://github.com/dimagi/commcare-hq#downloading-and-configuring-commcare-hq
