### ISSUE TITLE
[key-value-mapping] Don't allow multiple entries with the same key

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcare-hq#1967]
## Checklist:
- [ ] Show error in the input UI
- [ ] Do not allow the modal to save if there's an error
## Show error in the input UI

![screen shot 2013-11-20 at 9 34 28 am-1](https://f.cloud.github.com/assets/137212/1632333/34556dec-5776-11e3-97bd-e20d057d2837.png)

The row of the second occurrence of a key should have the key-input red-rimmed indicating an error, with a red error message "duplicate key" under it (make sure to use i18n). This can be achieved by adding the bootstrap css class `"error"` to the control-group.
### Hints

The knockout.js for-loop that generates each row in the screenshot above is here: [key_value_mapping.html](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/hqwebapp/templates/hqwebapp/key_value_mapping.html#L3) (the knockout template).
 (`sortable` is a custom knockout binding we wrote that is just like `foreach`, but makes the rows reorderable with drag-and-drop.)

You'll need to add an `itemIsDuplicate` method here [key-value-mapping.js](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/hqwebapp/static/hqwebapp/js/key-value-mapping.js#L47) (the knockout view-model), and then reference it in the knockout template.
## Do not allow the modal to save if there's an error

Clicking the x or clicking away from the modal closes the modal without saving and cancels any changes, so that's fine. Clicking OK commits the change locally on the client side and should not be permitted if there's an error. The OK button should grey and **and** be disabled (those are two separate things) and the text should change to Fix Errors.

**Comment by jessica-muremure** [comment]
FYI (6 years later): This is fixed! We should be able to close out this issue.

**Comment by dannyroberts** [comment]
Ha! Great, thanks @jessica-muremure
