### ISSUE TITLE
Docker builds are broken

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcare-hq#21319]
Follow up to https://github.com/dimagi/commcare-hq/pull/21279#issuecomment-407390889 from @emord

> @dannyroberts I think this may have affected the docker build: https://hub.docker.com/r/dimagi/commcarehq_base/builds/beukvh5qcgqnfodgs65tflj/
> 
> ```
>   Running setup.py develop for architect
> 
>     Complete output from command /usr/local/bin/python -c "import setuptools, tokenize;__file__='/src/architect/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
> 
>     running develop
>     error: can't create or remove files in install directory
>     
>     The following error occurred while trying to add or remove files in the
>     installation directory:
>     
>         [Errno 2] No such file or directory: '/vendor/lib/python2.7/site-packages/test-easy-install-1665.write-test'
>     
>     The installation directory you specified (via --install-dir, --prefix, or
>     the distutils default setting) was:
>     
>         /vendor/lib/python2.7/site-packages
>     
>     This directory does not currently exist.  Please create it and try again, or
>     choose a different installation directory (using the -d or --install-dir
>     option).
>     
> ```

**Comment by dannyroberts** [comment]
I ran this locally to try to reproduce

```
mkvirtualenv cchqtest
pip install -r requirements/requirements.txt -r requirements/test-requirements.txt
```

but it went through fine. Do you have an intuition of what you think might be causing this or how to reproduce? I think I'm at a bit of a loss.

**Comment by emord** [comment]
@dannyroberts It looks like docker isn't actually using virtualenv https://github.com/dimagi/commcare-hq/blob/275c5d3447008c36052c50ef90c893b8065c4f63/Dockerfile#L24-L30 Maybe that could be a factor?

**Comment by dannyroberts** [comment]
Build succeeded: https://hub.docker.com/r/dimagi/commcarehq_base/builds/
