### ISSUE TITLE
pip-compile produces different results on different operating systems

### ISSUE THREAD

**Issue by emord** [dimagi/commcare-hq#21580]
More context https://github.com/dimagi/commcare-hq/pull/21559#discussion_r210748977

It appears that ipython has different dependencies if you're on a mac vs linux. I think we should default to linux's requirements since that's what our servers run, but as of right now I don't know of a way to enforce that.

This isn't currently breaking anything, but it will probably create some package churn if we start using pip-sync, and could potentially break if a package requires conflicting dependencies on different platforms

fyi: @kaapstorm since you ran into this the other day

**Comment by dannyroberts** [comment]
Thanks for raising this; certainly an annoying issue.

I think the best way to ensure that these sorts of platform-dependent discrepancies don't crop up is to run `make requirements` in travis and assert that there's no resultant git diff. That way if someone with a mac commits something that would have come out differently on linux, that'll become clear right away.

I'd say for ipython in particular, other than minor convenience, I don't think there's a need to have it be in prod-requirements.txt at all; and for dev, it's probably worth including `appnope` directly with a custom directive telling it to only install on mac.
