### ISSUE TITLE
Regressions with new 'async' param for fixtures api

### ISSUE THREAD

**Issue by tobiasmcnulty** [dimagi/commcare-hq#24051]
I'm pretty sure #24025 introduced a requirement that the `async` param be included in the URL (even if false), just FYI (the request fails without it).

Also, it's putting a json blob in what used to be a text field (`message`):

```
[commcareapi.api] Message "Success calling commcare API to send lookup tables. Status = 200, reason = OK, response body = {"message": {"curl_command": "curl -v --digest https://www.commcarehq.org/a/inddex-caktus/fixtures/fixapi/status/dl-bc4980b0abed4b3d9d238d6cb4ef0f3a/ -u <snip>", "status_url": "https://www.commcarehq.org/a/inddex-caktus/fixtures/fixapi/status/dl-bc4980b0abed4b3d9d238d6cb4ef0f3a/", "download_id": "dl-bc4980b0abed4b3d9d238d6cb4ef0f3a", "message": "File uploaded successfully."}, "code": 200}"
```

Finally, I think the message "File uploaded successfully." might be somewhat misleading. The file has really been queued for processing; it's too early to tell if it was really "successful" or not...

**Comment by emord** [comment]
@tobiasmcnulty sorry for the delay in a response to you. I believe your first issue was solved that day by https://github.com/dimagi/commcare-hq/pull/24052

I have just submitted https://github.com/dimagi/commcare-hq/pull/24158/ which does not nest the JSON and also changes the text from "File uploaded successfully." to "File has been uploaded successfully and is queued for processing" Which I think more accurately describes the situation

**Comment by tobiasmcnulty** [comment]
Thanks @emord!
