### ISSUE TITLE
[CEP] Split data warehouse App Status DAG into smaller units

### ISSUE THREAD

**Issue by snopoke** [dimagi/commcare-hq#25468]
### Abstract
Split up the App Status [DAG](https://airflow.apache.org/concepts.html#dags) in the data warehouse into smaller, more atomic units.

### Motivation
Each DAG in the warehouse consists of a multiple steps. Each step must complete successfully in
order for the entire DAG to be marked as a success. The more steps there are in a DAG the more
chance there is of failure. If a DAG fails, each task is retried from the beginning meaning
that any incremental successes were lost.

The App Status DAG is particularly susceptible to this problem since the steps are very long and there is a lot of work that get's lost when the process fails.

### Specification
The current aggregation workflow for the App Status data is as follows:

![app status full](https://www.plantuml.com/plantuml/img/XP513eGW40JlyuhvW5_O-0_Z0H6G1C70UDZVho8cAh3UXkwYXmvj8EPfdGqO8Gd9eTTg8Xor5voqim1TH71WnASUc-Q3dNH-narMsgeUxiU3OCkoAxG6V8UZ91cdquxpMr3DoU_5v5AFyBNSE7K9VIftBhsn35qsrdFBpNB-Zrdh1vbsaCAEgJIqsxp_zGy0)

Failure at any stage required completely re-loading all the staging data and re-executing any
of the previous ETL steps, regardless of whether they were successful or not.

To solve the problem the workflow should be split up in to 4 loosely coupled workflows:

#### Form and Synclog workflow
These are very straight forward worflows that follow the simple pattern of loading data into 
staging tables and then writing that data into the fact table with some transformation and linking.

![form synclog](https://www.plantuml.com/plantuml/img/RP112iCW44Ntdc8ka2kKKAWNc6MGOeqQmIYOwQAthsDDca8tml_-zsTqt4WNUgvHHEi8A4C9VY6OGx66Gav2J3RDyD1a5WLwWzlrZdyyMOCkbnLgeG_9DrzYDvqsz74ujxsIYTd_H16__f76bkODeTNqYSDmWKcY4dnq9Ld9hdWVTQ1xxPb6fd6daMayqVLMZFMD_35l)

#### App status workflows
The App Status workflow differs only in that the data to populate the staging tables is taken
from other fact tables instead of from CommCare HQ models. 

![app status spearated](https://www.plantuml.com/plantuml/img/RP5D3eCW48Ntd68ke0VeeccRb0lCaX135NyI5OFZehSl8FxM5UJnPhx7p6CaPMdgMjRgae0CsAQg2Oh6wfmQqpCcT5_0Hr5UIr0Zl5_P4pFEhtNap5MKndPGgfp2Y_UEtpvlJRM9tYZKC80BGDC8eSJTgwQlWi53y61PUfnSYF-DLaoCUj5bRmbXmYJcylYh9Bc323aa4vnBICDmqbMzWTMgS4nhEXQrhOfB5izPMoOdLzYIvSH3pyCp3ozukEDXvE6HvsNsSBjoI_u1)

The requirements for making this work are as follows:

1. All data required to generate each of the app status workflows must be available in the
respective fact table.
    - This is already the case

2. A mechanism is required that will allow the app status workflows to only process new data 
(data that has not been processed since the last successful run). This appears to be the main
reason that data is taken from the form and synclog staging tables since those
tables only contain data from the most recent batch.

To solve the second requirement we can use the Batch records created for the form and synclog 
processes. The fact tables already contain an indexed column with the batch ID which is updated whenever a row is changed. 
We can use this to filter the fact tables for only data that has been changed
since the last successful run of the App Status workflow.

The pseudo code below illustrates this concept:
```python
app_status_form_batch_from_date = A
app_status_form_batch_to_date = B

form_fact_batches = get_successful_batch_ids('form_fact', gt=A, lte=B)

# filter fact data based on batch IDs
populate_app_status_form_staging(form_fact_batches)
```

In addition to filtering on `batch_id` we will also need to add a filter on `received_on` which is used to partition the `form_fact` table. This will allow the query planner to ignore partition tables out of range.

```python
app_status_form_batch_from_date = A
app_status_form_batch_to_date = B

form_fact_batches = get_successful_batches('form_fact', gt=A, lte=B)

earliest_received_on = form_fact_batches[0].start_datetime

form_fact_batch_ids = [batch.id for batch in form_fact_batches]
# filter fact data based on batch IDs
populate_app_status_form_staging(form_fact_batch_ids, received_on__gte=earliest_received_on)
```

### Impact on users
This is an internal change that should not impact end users except that it should make
the warehouse ETL process more reliable.

### Impact on hosting
Since these changes need to be made across CommCare HQ as well as Airflow it will be necessary to do a multi-stage rollout. However since only Dimagi controlled environments are running the data warehouse this can be fully controlled by Dimagi so there will be no extended support windows
required. 

### Backwards compatibility
The multi-phase rollout will ensure backwards compatibility until all environments have been upgraded. The rollout process is described below:

1. Create and deploy new ETL classes for the updated workflow.
2. Update airflow to use the new workflow and ETL classes.
3. Remove old ETL classes.

### Release Timeline
No specific timeline.

### Open questions and issues
None

**Comment by calellowitz** [comment]
Love both the new CEP format and this idea. Seems like a great improvement, especially if we can make the form fact components more incremental

**Comment by sravfeyn** [comment]
This is great idea!

Both `app status synclog fact` and `app status form fact` are same rows, right? Or are they going to create separate rows?

**Comment by snopoke** [comment]
@sravfeyn they update the same rows but in separate queries: https://github.com/dimagi/commcare-hq/blob/9dde804ff259bab84268ebedb3bd6497764640e0/corehq/warehouse/transforms/sql/app_status_fact.sql

**Comment by emord** [comment]
I added an ADR for removing the warehouse in https://github.com/dimagi/commcare-hq/pull/25652.

Should this issue be closed out?
