### ISSUE TITLE
[CEP] Change form ids from globally unique to unique within each app

### ISSUE THREAD

**Issue by orangejenny** [dimagi/commcare-hq#25718]
**Abstract**
Form IDs in HQ are currently expected to be globally unique, which over time has increased the complexity of the app copy and linked app workflows. This CEP proposes eliminating this constraint and instead guaranteeing form id uniqueness only within the app, the same expectation we have for module ids and for form xmlns.

**Motivation**

*Background on app copy and linked apps*
When an app is copied, each form in the copy is assigned a new unique id. This is necessary because several HQ workflows depend on form ids being globally unique.

When an app is copied, each form in the copy keeps the same XMLNS as the corresponding form in the original. XMLNSes must be unique within an app, but they do not need to be globally unique.

Linked apps use similar workflows to app copy for creating and pulling. Like an original/copy pair of apps, in a master/linked pair of apps, corresponding forms will have the same xmlns but different ids. For linked apps, it's specifically desirable that XMLNS be the same for corresponding forms on the master and linked app, because form-based UCRs typically filter based on XMLNS, so the same reports can be used on the master and linked app.

*Pulling linked apps*
As in app copy, when a linked app is created, each of its forms is assigned a new unique id. Form unique ids must be consistent between versions of the linked app due to a [mobile issue](https://dimagi-dev.atlassian.net/browse/ICDS-343) where mobile will crash if, from one update to the next, a form's unique id changes while its xmlns remains the same. The mobile issue has been fixed as of the 2.47.4 LTS, but it will be some time before all users will be on 2.47.4+

When the linked app is pulled, virtually all of its fields are overwritten by the current master app. After this overwrite, the forms' unique ids need to be set to the values they had before the pull. This is done by mapping XMLNS to unique id prior to the overwrite and then using that map to update ids after the overwrite. This mapping and updating is intricate and has been the source of bugs, most notably [ICDS-538](https://dimagi-dev.atlassian.net/browse/ICDS-538). To work around this issue, the ICDS team currently uses a multi-revert process for every release. Other complex projects that develop a similar "branching" process are at similar risk.

Multimaster linked apps were created in part to mitigate this problem. However, [UAT](https://dimagi-dev.atlassian.net/browse/ICDS-965) has run into similar behavior via a different workflow than ICDS-538. Multimaster improved but also complicated the id reassignment code.

*Linked apps and shadow forms*
Shadow forms are a variation of advanced forms that "shadow" another form's XML but can have their own settings and actions. Shadow forms don't have their own XMLNSes, which means they don't work with the xmlns => unique id mapping used while pulling linked apps. This results in shadow forms in linked apps having unstable ids that may change when the app is pulled, which makes them incompatible with any workflow that stores a form unique id.

*Improved engineering efficiency*
We've spent a fair amount of time fiddling with this logic over the years. This includes https://github.com/dimagi/commcare-hq/pull/17306/, https://github.com/dimagi/commcare-hq/pull/7919, https://github.com/dimagi/commcare-hq/pull/17250, https://github.com/dimagi/commcare-hq/pull/21872, https://github.com/dimagi/commcare-hq/pull/21969, and a good deal of the time spent on multimaster dev and testing. The re-assigning of IDs started out as very reasonable code, but the addition of linked apps and shadow forms has complicated it to the point where debugging and working around these issues is quite challenging; see [doc explaining the root cause of and workaround for ICDS-538](https://docs.google.com/document/d/1PtIpLZsmUqVmkK_umcbI9c6CUCCXq2sYQSgsf14YJkg/edit).

**Specification**
1. Update the following workflows, which expect form ids to be globally unique:
   1. ~~SMS surveys and structured keywords. This is the major change. These are based on just a form unique id and would need to be updated to also include an app id, and any related data would need to be migrated.~~ Done in https://github.com/dimagi/commcare-hq/pull/25757
   1. ~~[get_form_name](https://github.com/dimagi/commcare-hq/blob/b22b718bb698cd7d54b930962f983739a6877680/corehq/apps/reminders/util.py#L78) in reminders, which is only used in an IVR report. IVR was deprecated in January 2018 in https://github.com/dimagi/commcare-hq/pull/19056 but the report remains. Open question whether to fix this or kill the report.~~ Removed the `get_form_name` reference in https://github.com/dimagi/commcare-hq/pull/25740, opened https://dimagi-dev.atlassian.net/browse/SAASP-10113 to kill this report altogether.
   1. ~~CommCare Exchange, specifically [Domain.save_copy](https://github.com/dimagi/commcare-hq/blob/b22b718bb698cd7d54b930962f983739a6877680/corehq/apps/domain/models.py#L796) and the [SnapshotSettingsForm](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/domain/forms.py#L421-L425). There's an [open proposal](https://github.com/dimagi/commcare-hq/issues/25506) to deprecate the exchange that's currently working its way through product & BD. For the sake of this proposal, at least the share reminders functionality would need to be updated (not ideal) or removed.~~ Done in https://github.com/dimagi/commcare-hq/pull/25757
   1. ~~Report Builder's [FormDataSourceMeta](https://github.com/dimagi/commcare-hq/blob/9043175c9e8cc894fbbb6efd36c07010129f07b5/corehq/apps/userreports/app_manager/data_source_meta.py#L108) class. This should be a minor update.~~ Done in https://github.com/dimagi/commcare-hq/pull/25725
   1. ~~App manager's [get_form_data_schema](https://github.com/dimagi/commcare-hq/blob/b510fa9246f505a3743ccf78d653e9352035d8bc/corehq/apps/app_manager/views/formdesigner.py#L177) view. This has app id available and should be trivial to fix.~~ Done in https://github.com/dimagi/commcare-hq/pull/25724
1. ~~When forms are initially assigned an XMLNS, it's based on `uuid.uuid4`, but a form's xmlns can later be updated in [save_xform](https://github.com/dimagi/commcare-hq/blob/170690a2fbf8039365fdca852911b4a57fd70a1e/corehq/apps/app_manager/util.py#L159-L161) if the app contains duplicate xmlnses. The new xmlns is based on the form's unique id. See discussion in https://github.com/dimagi/commcare-hq/pull/17306 I don't think it's strictly necessary to change this but do think it would reduce confusion to instead base the new xmlns on `uuid.uuid4`.~~ Done in https://github.com/dimagi/commcare-hq/pull/25775
1. ~~Remove `FormBase.get_form` and `xforms_index` couch view.~~ Done in https://github.com/dimagi/commcare-hq/pull/25776
1. ~~Remove `LinkedApplication.uses_master_app_form_ids`.~~ Done in https://github.com/dimagi/commcare-hq/pull/25736
1. ~~Come up with a plan to store ID mappings for existing linked apps. Removing the form re-assignment code altogether will break linked apps on the next pull, because the form unique ids in the linked app would be overwritten by the master ids and not updated to the values the linked app had been using.~~ Done in https://github.com/dimagi/commcare-hq/pull/25803
1. ~~Remove form id re-assignment code in [Application.scrub_source](https://github.com/dimagi/commcare-hq/blob/b22b718bb698cd7d54b930962f983739a6877680/corehq/apps/app_manager/models.py#L5284) and [overwrite_app](https://github.com/dimagi/commcare-hq/blob/170690a2fbf8039365fdca852911b4a57fd70a1e/corehq/apps/app_manager/views/utils.py#L162).~~ ...Done in https://github.com/dimagi/commcare-hq/pull/25998

**Impact on users**
Minimal. It should make the multi-revert workflow process used by complex apps safer.

**Impact on hosting**
None

**Backwards compatibility**
No issues.

**Release Timeline**
Immediate, since this is currently a risk for ICDS and potentially blocking multimaster release.

**Open questions and issues**
~~What's the status of IVR and the Call Report?~~ Discussed with product and support, planning to remove this report altogether in a few weeks. Tracking this in https://dimagi-dev.atlassian.net/browse/SAASP-10113 Also opened https://github.com/dimagi/commcare-hq/pull/25740 to remove the specific part of the report that depends on `xforms_index`.

**Comment by snopoke** [comment]
This seems very reasonable to me and I don't see any blocker to having all places that use the Form ID also include the App ID

**Comment by esoergel** [comment]
I'm also in favor of this idea.

It might be useful to articulate the purpose of form unique IDs and form xmlnss, and how they differ.  Forms are already identifiable by XMLNS, except for shadow forms which don't have one.  Perhaps unique_ids then refer to the app manager concept of a form, whereas an XMLNS refers to an XML form definition?

**Comment by orangejenny** [comment]
Added some more items under Specification. Most of them are straightforward. The nebulous one is coming up with a plan so that existing linked apps, with form ids that differ from their master apps, continue to work even after the id-updating code is remove.

(Don't need additional feedback at this point, just fyi.)

**Comment by orangejenny** [comment]
All code related to this has been merged. Closing.
