### ISSUE TITLE
Reindexer breaks on forms missing xml attachment

### ISSUE THREAD

**Issue by esoergel** [dimagi/commcare-hq#25985]
From https://forum.dimagi.com/t/elasticsearch-transporterror/7017

In that forum issue, the `sql-form` reindxer fails hard upon encountering a specific form.  This form has `state = 'deprecated'` and `problem = "Missing form.xml"`.

The reindexer encounters that doc, calls [`doc_to_json`](https://github.com/dimagi/commcare-hq/blob/8e8243bc80964e6981fcb89a712776e9faf97397/corehq/util/doc_processor/sql.py#L58-L59), which calls [`get_xml`](https://github.com/dimagi/commcare-hq/blob/8e8243bc80964e6981fcb89a712776e9faf97397/corehq/form_processor/models.py#L480-L480), which of course raises `MissingFormXml`.

My question is - what's the appropriate handling here?  I see that `form_data` returns `{}` when there's a [problem](https://github.com/dimagi/commcare-hq/blob/8e8243bc80964e6981fcb89a712776e9faf97397/corehq/form_processor/models.py#L480-L484) with the XML structure, doing the same with missing xml would be an easy fix.  I also see [this block](https://github.com/dimagi/commcare-hq/blob/8e8243bc80964e6981fcb89a712776e9faf97397/corehq/form_processor/backends/sql/processor.py#L220-L224) of code, which skips processing of deprecated forms with errors.  Perhaps the reindexer should [exclude](https://github.com/dimagi/commcare-hq/blob/8e8243bc80964e6981fcb89a712776e9faf97397/corehq/form_processor/backends/sql/dbaccessors.py#L366-L374) those forms entirely? 

@snopoke @millerdev do you have insight on this?  I've seen your involvement on a couple vaguely related PRs, plus I imagine the couch-to-sql migration has needed to deal with this.
https://github.com/dimagi/commcare-hq/pull/25499
https://github.com/dimagi/commcare-hq/pull/24997

**Comment by millerdev** [comment]
Up to very recently the couch-to-sql migration has skipped over forms with missing form XML (note: it did not fail hard). It also recorded diffs in the diff db so we have a record of those unmigrated forms. In the past week I have been working on a solution to rebuild the form XML from the JSON stored in couch (it's actually quite easy to do). Unfortunately that solution will not work in SQL because forms are not stored as JSON there.

Would it be reasonable to have the reindexer catch `MissingFormXml` and skip the form?

**Comment by esoergel** [comment]
> Would it be reasonable to have the reindexer catch MissingFormXml and skip the form?

Yeah, I think that would be pretty straightforward to implement.  Do you think that's more correct than excluding deprecated forms up-front?  Guessing so, if there are myriad causes of deprecation.

**Comment by esoergel** [comment]
addressed in https://github.com/dimagi/commcare-hq/pull/25993

**Comment by millerdev** [comment]
> Do you think that's more correct than excluding deprecated forms up-front?

I'm not sure what the best answer is here, although maybe we want to do both? Deprecated forms are certainly not the only ones with missing XML.
