### ISSUE TITLE
[CEP] Allow Locations with children to be moved to new parents of the same type

### ISSUE THREAD

**Issue by esoergel** [dimagi/commcare-hq#26279]
**Background**
Rearranging the location structure is challenging for users and in the code.  Once upon a time, there was an "anything goes" approach to this, which resulted in all sorts of stuff that didn't fit the model - locations whose parents weren't of the proper parent type, cyclical parentages, locations not under any top-level location.

There was a lot of cleanup done to address the inconsistent data and force more constraints on what could be configured.  In doing so, I tended towards strictness if ever there were a doubt.  This (intentionally) made sweeping changes hard to do.

To address this, we introduced the current version of the location uploader, which lets you specify the entire locations structure as you'd like it to be (and now I believe certain subsets are valid too).  This uploader can validate the internal consistency of the proposed new state and apply it in full.  That seems to have largely met the needs, though it is a complex tool to use, and has performance concerns on projects with very large numbers of locations.  This has become a pain point.

One piece of low hanging fruit - in my opinion - is moving individual locations.  Doing so in theory brings along all child locations.  You cannot currently move a location with children in the UI.  There are two reasons for this that I'm aware of:

* Forcing a location type change
  * If the new parent is at a different level than the old, then the location needs to be of a different type to match.  Same goes for all child locations.  If any of these locations have multiple possible new types, a selection must be made.  We avoid this nondeterminism by prohibiting the action.
* Effects on stored fields
  * In the past, each location stored its entire ancestry, so such a move would require propagating a change to all child locations.  This was removed in the migration to SQL.
  * After that migration, the library we used for managing the tree structure internally stored state related to the full ancestry.  This meant that changes like this sometimes required rebalancing large numbers of locations.  This was removed in the migration to using CTE queries.  Locations now only store a foreign key to their direct parent, and one to their location type.

While the second point is no longer relevant, the first point is still valid.  However, it only applies to relocations to a new level, or more precisely, to changing a location's type.  Actually while writing this, I realized we don't currently prevent you from changing a location's type when it doesn't also necessitate a new parent (ie, with a forked type hierarchy), which I just confirmed can allow you to violate your location type schema.

**Abstract**
I propose removing the restriction on re-parenting locations with children, and replacing it with a restriction on changing the type of locations with children.

**Motivation**
This would bring more power to location changes in the UI.  My hope is it would meet the majority of use cases which would otherwise be forced to use the location uploader.  It should be a safer and more user-friendly approach for basic rearrangement needs.

**Specification**

**Impact on users**
extra flexibility

**Impact on hosting**
nope

**Backwards compatibility**
yup

**Release Timeline**

**Open questions and issues**
Does this have any potential for screwing up data in a way that isn't possible in the uploader?

If for example, a case manually stores the ID of a grandparent location, then that case's location is moved, the grandparent location is no longer accurate.  I think this is an acceptable risk, and it is currently present in reshuffling done via the uploader.

One could make the argument that this be expanded further - allowing location type changes where the downstream impacts would be deterministic.  That I think is less clear to end-users, and I'd prefer to leave it out of scope for now.

**Comment by snopoke** [comment]
@esoergel can this CEP be closed now?

**Comment by esoergel** [comment]
Yup, this is resolved, thanks for flagging.
