### ISSUE TITLE
[CEP] Partition synclog data into multiple databases

### ISSUE THREAD

**Issue by snopoke** [dimagi/commcare-hq#26381]
**Abstract**
Synclog records are currently stored in a single database. A new record is created for every sync request and past records for a `user, app_id, device_id` are deleted after a form submission has been received.

To allow spreading this data over more hardware resources this CEP proposes a partitioning schema that will allow the data to reside in different locations based on the `user_id` field.

**Motivation**
With 600K users ICDS has reached the limits of what a single DB VM can support without further vertical scaling. Considering that this load is not even half of full scale it makes sense to look at alternatives to vertical scaling.

**Specification**
Unlike case and form data which are partitioned by document ID, synclogs can be partitioned by the user ID. There are two reasons for doing this:

1. There are some queries where only the user ID is known. Partitioning by user ID makes these queries efficient since they can be run on a single shard.
2. Having the data for a user co-located makes it easy to prune old data.

Analysis of the usages of synclogs shows that all queries that appear outside of test code can be made to include the user ID (or don't need to in the case of aggregate queries).

The partitioning and query routing will be done in Django so no routing DB (e.g. plproxy) will be required. \

The data will continue to be kept separate in it's own set of databases. This allows the synclog cluster to scale independently and avoids adding more load to the OLTP cluster which is already under high load.

The data will continue to be stored in PostgreSQL databases.

**Impact on users**
None

**Impact on hosting**
The implementation will be done so that by default all of the logical shards exist in a single database which will be functionally the same as the current setup.
This will mean that there will be no changes for 3rd parties hosting CommCare.

**Backwards compatibility**
None

**Release Timeline**
ICDS is targeting mid February 2020 to release this.

**Open questions and issues**

* Will this require another plproxy node?
  * No. The access patterns allow virtually all queries to be directed to a single node. This routing can be done from Django directly.
* Why not use the current sharded database instead of adding another one?
  * Keeping this data separate avoids adding more load on the the current OLTP databases.
* Why not move to MongoDB (or some other NoSQL database)
  * Introducing a completely new database will have additional cost implications on the team in terms of setup, maintenance etc. There is also no reason to move since the current technology is working well.
* Why not move to CitusDB?
  * It would require an additional VM for the controller node. 
  * Future expansion would require purchasing an enterprise license (or developing our own tooling).
  * The simplicity of the synclog data access patterns does not warrant the complexity of CitusDB.

**Comment by sravfeyn** [comment]
Quick question on background:
What exactly is hitting the limits currently on SyncLog DB, is it concurrent number of queries, or the size of the DB or something else? Given that almost all users use a single device ID and submit against a single app ID, the number of rows would ideally be linear in terms of number of users which is probably not very high at full scale also, so I am assuming we are sharding to be able to scale number of concurrent queries?

The approach sounds great, since it can be done inside Django itself.
- Sharding on user-id sounds good, just curious if you thought about sharding on sync date, and compare it with user-id.
- Does the access pattern fit the use case of redis?

**Comment by sravfeyn** [comment]
Great CEP btw, thanks!

**Comment by snopoke** [comment]
@sravfeyn it is both data size and request load. I had meant to include some more analysis which I've now done:

![image](https://user-images.githubusercontent.com/249606/72258111-e73d7880-3615-11ea-8705-c22bcf5b6a76.png)

Data size is currently 3.5T. While doing the analysis I realised that the size of data does not nearly match up with the size of the records and the number of records. This does make sense since we do delete a lot of records but the storage space is only reclaimed by doing a VACUUM FULL which we don't do.

I tested using [pg_repack](https://reorg.github.io/pg_repack/) on one table and it dropped ffom 650GB to 5GB which is very promising. I'm going to repack the remaining tables which should reduce the disk size dramatically and hopefully also the performance. I'll leave this open for now but it may not be necessary after all.

**Comment by snopoke** [comment]
Disk usage dropped to 200GB:
![image](https://user-images.githubusercontent.com/249606/72327738-59679900-36ba-11ea-81f1-223bd9e2b341.png)

I'm going to leave this for now and implement daily repack instead. I'm going to leave this open for now though and revisit later.

**Comment by esoergel** [comment]
This proposal is very clear and seems appropriate for the issue.  Have you given much thought yet around how HQ code will interact with the database when using sync logs?  Will this introduce a new DB interface, or intercept requests using the existing methods of talking to SQL?  Is there a risk of future synclog changes tested only in single-sharded settings breaking functionality on ICDS?

**Comment by sravfeyn** [comment]
That's a great drop in storage! Yeah, sounds great if reclaiming the storage results in performance improvements as well. If we don't use standby for reads, we can keep toggling standby and master periodically and run the FULL VACUUM on the standby, so that downtime is not required and we will always have small disk footprint?

**Comment by snopoke** [comment]
> If we don't use standby for reads, we can keep toggling standby and master periodically and run the FULL VACUUM on the standby, so that downtime is not required and we will always have small disk footprint?

@sravfeyn we're using pg_repack to run the vacuum which doesn't require downtime. I'm in the process of writing a script to run it automatically.

**Comment by snopoke** [comment]
> Have you given much thought yet around how HQ code will interact with the database when using sync logs? Will this introduce a new DB interface, or intercept requests using the existing methods of talking to SQL?

@esoergel I had planned to use our existing `PartitionedModel` class and abstract it slightly more so that we would end up with something like this:
```python
class PatitionedModel(models.Model):
    ...

class PlProxyModel(PatitionedModel):
    ...
```

The actual routing would be handled in the DB router (as it is now) but we'd need to be able to do the sharding for different 'clusters' which would share most of the logic except to which DBs the shards are assigned:

```python
def db_for_read_write(model, write=True, hints=None):
    if app_label in (FORM_PROCESSOR_APP, SCHEDULING_PARTITIONED_APP):
        return get_read_write_db_for_partitioned_model(model, hints, write, cluster='form_case')
    if app_label == 'synclogs':
        return get_read_write_db_for_partitioned_model(model, hints, write, cluster='synclogs')    

def get_read_write_db_for_partitioned_model(model, hints, for_write, cluster=None):
    db = get_db_for_partitioned_model(model, hints, cluster)
    if for_write or not allow_read_from_standby(cluster):
        return db
    return select_db_for_read(db, cluster)
```

> Is there a risk of future synclog changes tested only in single-sharded settings breaking functionality on ICDS?

All the routing can be tested in unit test without the need for setting up databases so I don't think this will be an issue. This is how we test the routing to standbys since we don't have any standbys in our unit test environment.
