### ISSUE TITLE
Multi-Pillow Processor that doesn't use a separate process for each Pillow

### ISSUE THREAD

**Issue by yedi** [dimagi/commcare-hq#2775]
Currently, the way we leverage pillows is by creating a separate supervisor task for running each pillow. Each pillow then has it own changes stream listener which it listens to for keeping up to date with the ongoing couch changes. 
#### This is useful because:
- each pillow can keep track of it's own sequencing (really useful for preindex workflows)
- processing speed for any given pillow doesn't affect any other pillows processing speed
#### This is not great because:
- each pillow requires it's own worker. The supervisor tasks are simply `run_ptop` management commands. Each management command has non-trivial memory usage when it's running. Soon we'll reach a point where pillows are taking up too much memory on our machine.
- we're relying on couch filters to filter out the docs we don't want. This results in a slower `ChangesStream`, especially when there are multiple consumers. Because there isn't any intelligent caching, this also means that if there are two pillows that are using the same couch_filte, that filter function will get called twice for each doc that comes through the feed
## Potential Solution

My proposal is to switch from a multiple consumer architecture where each pillow reads off it's own personal changes feed, to an architecture where 1 consumer can handle the processing for multiple pillows.
### How I imagine this getting implemented
1. For each pillow add a `doc_filter` function. The changes feed can only take 1 couch filter for filtering docs, since we want to only use 1 changes feed consumer, we'll have to do the filtering in python. (This is apparently faster anyways, and we can be more intelligent with caching here)
2. Create a simple `ChangesStreamPillowConsumer` (great name!) service that given a mapping of doc filters (in python) to asynchronous tasks, will call the asynchronous celery task on every doc that comes in and passes it's doc filter.
3. Create a helper function that creates anonymous tasks for a pillows `process_change` fn. Or create an anonymous task that can delegate to the correct pillows `process_change` fn
4. Hook up the `ChangesStreamPillowConsumer` with the task(s) from 3.
### Caveats
- Preindexing is still a concern. I think we can just use leverage the existing preindexing workflows. When starting the preindex we can store the current seq of the running `ChangesStreamPillowConsumer` run the preindex tasks up to that point. Then when deploying next restart the `ChangesStreamPillowConsumer` from the old seq. (Or maybe start off a second `ChangesStreamPillowConsumer` with pillows pointed to a different ES index and run it after the preindex jobs have been completed. Then shutdown the initial consumer)
- Size of the rabbitmq queue might become problematic if a pillow is very behind.

**Comment by snopoke** [comment]
FYI @sravfeyn

**Comment by czue** [comment]
@snopoke @sravfeyn is this still relevant?

**Comment by snopoke** [comment]
This is not relevant any more since it has been implemented.
