### ISSUE TITLE
[CEP] Migration alerts before deploy

### ISSUE THREAD

**Issue by esoergel** [dimagi/commcare-hq#27838]
## **Abstract**
The aim of this work is to better communicate to deployers what changes are about to be deployed.

We currently use tags on pull requests to flag pull requests that have, for instance, a reindex or migration.  This information should be presented to deployers at the very beginning of the deploy process, as part of the “are you sure you want to deploy?” message.

## **Motivation**
Deployers are usually unaware of what exactly they are deploying, particularly as 3rd parties are hosting their own instances, and as the Divisions at Dimagi operate independently.  This is intended as a means for PR authors to communicate with deployers.

### Current state
When deploys happen, [we use git tags](https://github.com/dimagi/commcare-cloud/blob/3d9370aeaa2d78b4d036d698ccad57e601c7bf59/src/commcare_cloud/fab/utils.py#L85-L96) to label the commits that have been deployed to each environment.  At the end of the deploy, we then [generate a github URL](https://github.com/dimagi/commcare-cloud/blob/3d9370aeaa2d78b4d036d698ccad57e601c7bf59/src/commcare_cloud/fab/utils.py#L118-L134) which compares this deploy to the previous one.  The deploy scripts then [pass this information](https://github.com/dimagi/commcare-cloud/blob/3d9370aeaa2d78b4d036d698ccad57e601c7bf59/src/commcare_cloud/fab/operations/release.py#L342-L358) to a management command, [record_deploy_success](https://github.com/dimagi/commcare-hq/blob/1cbafaaf72d864a295fb0317b000b44a39c522e2/corehq/apps/hqadmin/management/commands/record_deploy_success.py,) which emails it to admins, and creates [a record](https://github.com/dimagi/commcare-hq/blob/1cbafaaf72d864a295fb0317b000b44a39c522e2/corehq/apps/hqadmin/models.py#L18-L18) of this deploy for later reference.

One glaring issue with this approach is that saving git tags requires write access to the repository, so this is fully off-limits for third-party environments, which deploy the Dimagi-controlled HQ repo.  Another limitation is that information about deploys is only presented after the deploy is complete, so it can’t be used to warn of potential concerns or special considerations.

### Desired changes

This can happen entirely inside `commcare-cloud/fab/`.

- Add a function to get a list of PRs between [`last_commit_sha`](https://github.com/dimagi/commcare-cloud/blob/3d9370aeaa2d78b4d036d698ccad57e601c7bf59/src/commcare_cloud/fab/utils.py#L65-L65) and [`deploy_ref`](https://github.com/dimagi/commcare-cloud/blob/3d9370aeaa2d78b4d036d698ccad57e601c7bf59/src/commcare_cloud/fab/utils.py#L138-L138).
- Extract tag information for each of these pull requests
- Render this list of pull requests to the console, displaying each PR's name, a link to the PR, and all its tags.  If any of those PRs are tagged `reindex/migration`, add a message in red to the bottom along the lines of "Warning!  You are about to deploy the following PR(s), which will trigger a reindex or migration.  Click the link for additional context", and repeat those PRs.
- Insert this message [here](https://github.com/dimagi/commcare-cloud/blob/3d9370aeaa2d78b4d036d698ccad57e601c7bf59/src/commcare_cloud/fab/fabfile.py#L648-L654).

## **Impact on users**
None

## **Impact on hosting**
Should reduce the communication gap between code authors and deployers.

## **Backwards compatibility**
Backwards compatible

## **Open questions and issues**

**Comment by millerdev** [comment]
+1 I like it.

> One glaring issue with this approach is that saving git tags requires write access to the repository, so this is fully off-limits for third-party environments...

Does this CEP address this issue? I don't see how the proposed changes affect it, but I agree that it is annoying (although seems irrelevant here). Maybe it needs a separate CEP?

**Comment by esoergel** [comment]
@millerdev 

Yeah, I initially thought we'd need to save a commit history in HQ and reference that in order to do the diff.  I was like 3/4 of the way through writing this when I saw the fallback clause [here](https://github.com/dimagi/commcare-cloud/blob/3d9370aeaa2d78b4d036d698ccad57e601c7bf59/src/commcare_cloud/fab/utils.py#L64-L70) - that we can just check against the current code in the repo, and that we _already do that_ :facepalm: 

I do still think saving the commit directly is a saner state for that stuff, but since it's not directly relevant to this CEP anymore, I spun that off separately.

**Comment by esoergel** [comment]
implemented in the above PRs.
