### ISSUE TITLE
[CEP] runtime configurable settings

### ISSUE THREAD

**Issue by snopoke** [dimagi/commcare-hq#29034]
### Abstract
This CEP outlines possible approaches to creating settings / config parameters that are configurable at runtime.

### Motivation
In certain cases it is useful to be able to change settings at runtime. This can be used to react to changes in usage of the platform or to adjust how certain features work without having to do a code deploy or config deploy + restart.

#### Option A
Define a new model for this use case

```python
class DynamicSetting(models.Model):
    slug = models.SlugField()
    serialized_value = JsonField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    @property
    def value(self):
        return self.serialized_value["value"]

    @value.setter
    def value(self, value):
        self.serialized_value["value"] = value


# setting definition and defaults
param1 = DynamicSettingDefinition('string_param', field=forms.CharField(label="String Param", initial="default", help_text=""))
param2 = DynamicSettingDefinition('integer_param', field=forms.IntegerField(label="Int param", initial=20, help_text=""))

# the setting is accessed via the static definition which controls access to the DB value
param1.value

# the setting is changed via Django admin
```

#### Option B
Add metadata to toggles.

This allows storing additional metadata in the Toggles data model.

**PROS**
- ties the config data to the toggle usage which is great when you want to configure a feature flagged feature
- re-uses an existing model rather than creating a new one along with the existing toggle UI

**CONS**
- doesn't lend itself to use without a feature flag
- extends the usage of CouchDB

```python
# data is stored in the Toggle model
class Toggle(Document):
    ....
    metadata = DictProperty()


# available keys are defined in the static toggle definition
toggle = StaticToggle(
    "slug", ....,
    metadata_definition={
        "param1": forms.CharField(label="String Param", initial="default", help_text=""),
        "param2": forms.IntegerField(label="Int param", initial=20, help_text="")
    ]
)

# the setting is accessed via the static toggle

toggle.metadata["param1"]
```

### Impact on users**
None

**Impact on hosting**
None

**Backwards compatibility**
NA

**Release Timeline**
NA

**Open questions and issues**

- Should JsonObject classes be used to define the types.

**Comment by czue** [comment]
You may already know this, but you can hack dynamic booleans with `PredictablyRandomToggle` and values of `0` and `1` which works fine. But if you need the settings to be a string or complex type then it's not possible.

Is there a first target use case for this feature?

My "didn't think too hard about it" gut instinct is Option A - though it would switch to B if we ever wanted to dynamically change a setting at a user or domain-level and not site-wide.

**Comment by snopoke** [comment]
> Is there a first target use case for this feature?

What made me think of this was defining these constants which we may want to be able to tweak dynamically:
https://github.com/dimagi/commcare-hq/pull/29033/files#diff-3f8e827dc128b4060168ea6aa08e34e7968be89eaff9f29ea3431df144628ab6R17-R19

I know we have a specific model for dynamic rate limits.

Some other things that come to mind:

* Blocked email domains (currently a toggle with a custom namespace)
  * this half suits a toggle since there are good features for caching and checking if an item is 'enabled'

I don't have any other use cases in mind which probably suggests this isn't useful enough.

> My "didn't think too hard about it" gut instinct is Option A - though it might switch to B if we ever wanted to dynamically change a setting at a user or domain-level and not site-wide.

Per domain configs is an interesting thought but I think that would current be done as a field on the Domain object (though they should likely also be moved to SQL)

**Comment by millerdev** [comment]
Option A: questions

The code snippet shows implementation of `DynamicSetting` and references `DynamicSettingDefinition`, but does not specify how they are related. Are they the same thing?

Your design doesn't say anything about using Redis, but that seems like a possible choice to store values that will be read frequently and updates must be shared amongst running processes. Was that implied or will the value be read from postgres each time it is accessed?

Option B: -1 because

> extends the usage of CouchDB

Please, let's not do this. I really want to see us prioritize eliminating Couch. It's a liability.

> **Open questions and issues**
>
> Should JsonObject classes be used to define the types.

-1 on JsonObject because it has a non-standard object interface. I know the Python object/attribute protocol pretty well, but my instincts about what will happen when interacting with a JsonObject are frequently wrong. `attrs` is a much better choice IMO.

**Comment by snopoke** [comment]
@millerdev I didn't include the caching aspect in the spec but this would have to cache the values in redis to make it performant.

`DynamicSetting` is the data model and `DynamicSettingDefinition` is just a python model to define the available settings, somewhat analogous to `Toggle` and `StaticToggle`.

I'm going to close this as I don't think there's a real need for it.
