### ISSUE TITLE
[CEP] Allow filtering by privileges on Exchange

### ISSUE THREAD

**Issue by ctsims** [dimagi/commcare-hq#30392]
**Abstract**
Allow the CommCare Exchange to support apps which include features that may not be available on community plans by filtering incompatible apps from the exchange page.

**Motivation**

Ticket: https://app.asana.com/0/1200837608877247/1200975747737456

We would like to release an app on the exchange that requires the Android Callout question type to accelerate the rollout of systems to facilitate RDT usage. The current exchange, however, would allow that app to get imported to spaces which couldn't use the core question type. We'd like to simply restrict access to apps based on the current project space.

This change will generally expand the utility of the exchange by letting us share more powerful apps for audiences who can utilize them.

**Specification**
The Exchange Application model will be extended to contain a list of required privileges for an app, which will need to be manually populated by the person entering the app into the exchange. When applications are listed, those which require a privilege unavailable in the current domain won't be displayed to the user for importing. 

These privileges will be entered as a space separated list of the privilege slug ids into a string field in on the Exchange Application record. Admin users are already entering dangerous fields into this model directly, so this isn't introducing new risk. Failures to enter data in the appropriate format pose less risk than other errors since the consequences are limited to whether the tile appears.

**Impact on users**
Users will still be able to see all apps which they are able to import, just as is true today. 

Users in multiple project spaces may see different sets of apps appear in the exchange between different project spaces.

**Backwards compatibility**
N/A - All existing apps are community only and will remain available.

This approach will rely on the existing Privileges framework in use to restrict features by plan, and doesn't introduce any new maintenance concerns.

**Release Timeline**
We'd like to have this complete by the end of September

**Open questions and issues**
None yet

**Comment by orangejenny** [comment]
Sounds fine.

**Comment by millerdev** [comment]
> The Exchange Application model will be extended to contain a list of required privileges for an app, which will need to be manually populated by the person entering the app into the exchange.

Would it make sense to pre-populate the list with a default set of privileges that matches the ones that are enabled for the project space of the source app? I don't know much about the exchange, so maybe that list is not even available at the time of publication on the exchange? If not, ignore this comment.

Otherwise seems good to me.

**Comment by ctsims** [comment]
> Would it make sense to pre-populate the list with a default set of privileges that matches the ones that are enabled for the project space of the source app? I don't know much about the exchange, so maybe that list is not even available at the time of publication on the exchange? If not, ignore this comment.

It's a bit tricky, but worth noting here in case this comes up as a point of future work.

Information about the privileges that are enabled in the source domain are available, but since we are the authors of the template apps the domains themselves are generally "everything enabled." We also publish multiple apps from the same space with potentially different privilege requirements.

Some of the different privileges **do** have the ability to infer privileges in use within an app (I found code specifically, for example, that identifies intent callouts), but it's not super consistent and is definitely pretty time consuming.

We pull the info about builds in ~real time when we load the exchange (there's no "publish to exchange" action, the exchange pulls the latest starred build). So if we want to pursue in the future, what we'll probably need to do is do those somewhat expensive inferences at build time  (or more likely when the build is elevated to a release) and cache the results for future filtering.

**Comment by ctsims** [comment]
Resolved in https://github.com/dimagi/commcare-hq/pull/30393
