### ISSUE TITLE
[CEP] CommCare Query Language for Case Search

### ISSUE THREAD

**Issue by snopoke** [dimagi/commcare-hq#31162]
# Abstract
Currently we use 'xpath' for parsing query expressions to generate Elasticsearch queries for case search. In some places we even call it Xpath (`_xpath_query`).

This CEP proposes that we break away from the XPath syntax to allow us to develop a more expressive query language that more closely aligns with how the queries are evaluated.

# Motivation
Although we are parsing the queries as XPath we are not trying to make them behave like XPath. One prime example of this is our syntax for querying ancestor cases:

```
parent/parent/name = 'joe'
```
In XPath that would indicate a traversal *down* the hierarchy and not *up*.

We also only support expressions that result in a 'binary expressions' that evaluate to a boolean.

Further more, we do support XPath on Mobile / Web Apps so the more we make this query language appear to be XPath the more likely there is to be confusion about what is supported in one or the other.

# Specification
The current base spec would match our [existing capabilities](https://confluence.dimagi.com/display/saas/Case+List+Explorer#CaseListExplorer-SearchExpressions) with the addition of set operations as a mechanism of querying related cases.

An example parser that support the current query features and set queries has been made [here](https://gist.github.com/snopoke/b67352a911ccc96b8c1ef4080a27d04a).

### Why do we need them?
1. You can't filter case based on their subcases

2. Filtering by ancestors is restrictive and has poor performance characgeristics.
    
    You can query ancestors using the `parent/parent/name = 'bob'` syntax it is very restrictive and only allows filtering on a single property of the ancestor at a time. Filtering on multiple properties requires doing this:
    
    ```
    parent/name = 'michaela' and parent/is_active = 1
    ```
    The result of this is multiple join queries which is very inefficient and non-performant.

### Set query syntax
Set queries allow creating a filtered set of cases and then by applying modifiers to the set we can join it with the parent query and use it for filtering.

**Filter on subcases**
```
{age > 3 and active = 1}.subcase('parent').exists()
```

**Filtering on supercases (parent, host, ancestor)**
```
{age > 3 and active = 1}.supercase('parent').exists()
```

**Nesting**
```
{age > 3 and active = 1 and {@case_type = 'lab' and result=1}.subcase('parent').exists() }.subcase('parent').exists()
```

## Alternatives
These alternatives make use of existing XPath syntax and so can still be parse using the Xpath parser. The main argument against these is it pushes us further int 'XPath' territory and blurs the lines between in-app and case search xpath support.

**Function**
```
subcase_exists('parent', age > 3 and active = 1)
# nesting
parent_exists('parent', age > 3 and active = 1 and parent_exists('parent', result = 1))
```

**Predicates**
```
subcase_exists[identifier='parent'][age > 3 and active = 1]

# alternative for ancestor queries which is an extension of the current syntax
parent[age > 3 and active = 1]/parent[name='joe']
```

See  https://github.com/dimagi/commcare-hq/issues/31118 for more details on the ancestor predicate version.

# Impact on users
Give users more expressive queries that perform better.

# Impact on hosting
None

# Backwards compatibility
Existing queries will continue to work

**Open questions and issues**

**Comment by snopoke** [comment]
Update:

We did not go for the set query syntax because it is more complex for users to grasp. Instead we chose the function syntax:
```
subcase_exists('parent', age > 3 and active = 1)
# nesting
parent_exists('parent', age > 3 and active = 1 parent_exists('parent', result = 1))
```

**Comment by millerdev** [comment]
The nested syntax is a bit curious because of the lack of operator between `active = 1` and the nested `parent_exists(...)` clause. To me that looks like an error, but I assume it's not since it's repeated in the CEP body as well as your follow-up comment.

Does that have the same meaning as this?

```
parent_exists('parent', age > 3 and active = 1 and parent_exists('parent', result = 1))
```

What if I want `or`? Could I do this?

```
parent_exists('parent', age > 3 and active = 1 or parent_exists('parent', result = 1))
```

Or is there something else going on that I'm missing?

Can you point to an XPath spec where this predicate matching syntax is defined?

**Comment by proteusvacuum** [comment]
I think this is an interesting question. Does your second message mean that this CEP is no longer under consideration? 

When we first built this, the reason we chose to use this "XPath-like" query syntax was to provide some consistency in how non-technical end users would write these queries. The way we thought about the search box was as if it was a predicate expression that resulted in a list of nodes - or in commcare, like creating a case list filter. I guess this feature has potentially outgrown that syntax.

I think this is more of a product question than a technical one, and with SaaS planning on releasing the CLE as a GA feature, they might have some interesting opinions here. My worry in creating a new query language is that it is yet another thing for users to learn, that is somewhat similar, but just different enough from XPath for it to be confusing (our original discussion around this is here: https://docs.google.com/document/d/1yz5Ysm0or9vi_OTxveDWcLCo6an09FHhsdSiYKO5dZQ/edit?disco=AAAABf_IvMI).

One of the hardest parts about this is to not expose the user to the implementation details of how our data is stored / indexed.

However, if we are really thinking about making a new query language for use in case search, I would strongly advocate to using a "well known" or "standard" query language - and given our user base, I would say this would ideally be some well defined subset of SQL.

**Comment by snopoke** [comment]
> The nested syntax is a bit curious because of the lack of operator between `active = 1` and the nested `parent_exists(...)` clause. To me that looks like an error, but I assume it's not since it's repeated in the CEP body as well as your follow-up comment.

That is indeed an error. I'll update the comment and the body. Thanks.

**Comment by snopoke** [comment]
@proteusvacuum thanks for the follow up. I've tried to address your points below:

> When we first built this, the reason we chose to use this "XPath-like" query syntax was to provide some consistency in how non-technical end users would write these queries. The way we thought about the search box was as if it was a predicate expression that resulted in a list of nodes - or in commcare, like creating a case list filter. I guess this feature has potentially outgrown that syntax.

I think there are two points here, one around syntax and another around meaning of the syntax.

On the syntax point, the main reason we landed on the *function* style instead of the *set query* style is because it most closely aligns with what users are already familiar with and it is still valid XPath syntax.

In terms of the meaning of they syntax:

1. Although we use XPath syntax we do not follow xpath rules, specifically with the ancestor queries. You could argue that if you invert the hierarchy and nest the ancestors inside each case then the query makes sense from an XPath point of view but I don't think that's how most people's mental model works (unverified claim).
2. It is already different from how it works in apps, different enough that I think creating more separation between the two is probably helpful. In some places we even mix the two query languages together which can make things even more confusing. Calling them both XPath compounds that confusion.

    ```
    concat("owner_id = '", instance('commcaresession')]/session/data/user_id, "' and age > 3")

    # evaluating the above expression in the app results in the follow Case Search query:

    "owner_id = '061ecbae-d9be-4bb5-bdd4-e62abd5eaf7b' and age > 3"
    ```

    Perhaps this is just a user interface problem we need to solve but I mention it since it is a problem we have currently.

> I think this is more of a product question than a technical one, and with SaaS planning on releasing the CLE as a GA feature, they might have some interesting opinions here. My worry in creating a new query language is that it is yet another thing for users to learn, that is somewhat similar, but just different enough from XPath for it to be confusing (our original discussion around this is here: https://docs.google.com/document/d/1yz5Ysm0or9vi_OTxveDWcLCo6an09FHhsdSiYKO5dZQ/edit?disco=AAAABf_IvMI).

Unfortunately that doc doesn't really come to any conclusions but it does mention Lucene syntax and SQL. I don't think either of those are good choices and would likely make it harder to query. I also note that the doc does not deal with the ancestor queries at all which is likely the most critical piece since it deviates furthest from the in app XPath.

The point of a DSL is to make it easier to work with the nuances of specific data structures. SQL is designed to query relational tables, Lucene is designed for searching documents. We use XPath in our apps because we represent the data as XML documents and the XPath queries match that:

```
instance('casedb')/casedb/case[@case_type='person']
      [@status='open']
      [index/parent=instance('commcaresession')/session/data/parent_id]
```

If we truly wanted to remain consistent we should support exactly the same queries. I think the reason we didn't in the first place (correct me if I'm wrong) is because it adds complexity that isn't needed for these queries and as you mentioned so as "to not expose the user to the implementation details of how our data is stored / indexed".

I think the suggested *function* syntax is both familiar to our users and also does not expose anything about how the data is stored. It creates a way to query the data by intent: "find cases that have at least one child with age > 3" rather than by data structure.

> However, if we are really thinking about making a new query language for use in case search, I would strongly advocate to using a "well known" or "standard" query language - and given our user base, I would say this would ideally be some well defined subset of SQL.

I disagree with this. As I mentioned SQL is designed for querying relational tables and forces you to think in that way. We could indeed use it for querying but we'd soon get into joins and sub-queries which are arguably not easy to use. I'll also mention that [Elasticsearch already support SQL syntax](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-overview.html) but it is limited to 'single table' queries which makes sense since ES doesn't support native joins. If we did not want to support ancestor / subcase queries then SQL may be a good option but having to support those as well makes it more complex. 

> Does your second message mean that this CEP is no longer under consideration?

The CEP is still under consideration but unless there are any major objections or improvements we (USH) are going to go ahead with implementing the *function* syntax to meet the needs of our current projects.

**Comment by snopoke** [comment]
Also just to note since it's relevant to the discussion, we are also expanding the Case Search query language to support the following functions for querying cases which have multi-valued properties (properties that contain multiple values separated by spaces):

* `selected(property_name, 'value')`

    Matches documents where `property_name` contains the string 'value' as a distinct value. This matches the existing XPath function already available in apps.

* `selected-all(property_name, 'value1 value2')`

    Matches documents where `property_name` contains all of the terms 'value1' and 'value2' as distinct values (irrespective of order).

* `selected-any(property_name, 'value1 value2')`

    Matches documents where `property_name` contains any or all of the terms 'value1' and 'value2' as distinct values.

Ref: https://docs.google.com/document/d/1fxb7kUw-GtCitJJIA_vTs8hZVKb7oqCRoMmpyQeRobY/edit#

**Comment by millerdev** [comment]
No objections here.

---

Re: nesting syntax error

That makes a lot more sense. Thanks for fixing.

I know _Set Query_ syntax has been ruled out, but for clarity on the proposed syntax, is there also a _missing `and`_ syntax error in the _Nesting_ expression?

```diff
- {age > 3 and active = 1 {@case_type = 'lab' and result=1}.subcase('parent').exists() }.subcase('parent').exists()
+ {age > 3 and active = 1 and {@case_type = 'lab' and result=1}.subcase('parent').exists() }.subcase('parent').exists()
```

**Comment by esoergel** [comment]
I don't have anything to add here other than that this looks cool.  Have you already discussed this issue with technical app builders?  I'd be interested to hear from the target user base, especially those who are more familiar working with apps and casedbs than elasticsearch.

**Comment by snopoke** [comment]
> Have you already discussed this issue with technical app builders? I'd be interested to hear from the target user base, especially those who are more familiar working with apps and casedbs than elasticsearch.

The general consensus was that function syntax is already used and understood. There was some debate over the naming:

1. subcase-exists
2. reverse-index-match
3. child-case-exists

(3) appears to make the most sense but there is ambiguity about extension cases
(2) is most technically correct but also most foreign to users

**Comment by millerdev** [comment]
I know you didn't ask for a vote, but I think my preference is (1) subcase-exists. It appears that we do have some places where we already refer to extensions as subcases (`ag subcase | grep extension`), in code anyway.

**Comment by snopoke** [comment]
Resolved by https://github.com/dimagi/commcare-hq/pull/31115

**Comment by snopoke** [comment]
See also https://github.com/dimagi/commcare-hq/pull/31187
