### ISSUE TITLE
[CEP] Custom repeater URLs with UCR expressions

### ISSUE THREAD

**Issue by proteusvacuum** [dimagi/commcare-hq#31413]
**Abstract**

In a Configurable Repeater, we want to be able to modify the URL based on the forwarded document such that we can include both a resource ID and any required parameters.

**Motivation**

Our repeater / forwarding framework currently supports sending `PUT`, `POST`, and `DELETE` verbs to an HTTP endpoint. We can currently modify the body of the request using UCR expressions, however, it isn't possible to modify the URL that we send data to.

Restful APIs often expect requests such as `PUT` and `DELETE` to be resource specific, for example: `/{base_url}/{item_id}?param1=foo&param2=bar`.

**Specification**

Define a "URL template" which uses named expressions to populate the URL:

- **Desired URL**: `/deadbeef12345?param1="DELETE"`
- **URL Template**: `/{case_id}?param1="{param_1}"`
- **Sample Named Expression Dict**:

    ```json
    {
        "case_id": {
            "type": "constant",
            "constant": "deadbeef12345"
        },
        "param_1": {
            "type": "constant",
            "constant": "DELETE"
        }
    }
    ```

Using the `{}` placeholders would be populated by a named expression stored in the same repeater (or in the named expression registry).

The URL template will be at the repeater level, and would be appended to the base url defined in the connection settings. The template can be used for a repeater with any HTTP verb currently supported by the framework.

For requests that don't require a body, this can be omitted from the repeater definition.

**Impact on users**

This is purely new functionality, and will allow users to have more flexibility when defining integrations to third-party tools.

**Impact on hosting**
None

**Release Timeline**
This is part of the work for the Jamaica vaccine certificates: https://dimagi-dev.atlassian.net/browse/SC-2032 

**Open questions and issues**
- URLs that result from a template that are subsequently invalid may cause the repeater to fail. The repeater framework currently messages an admin when this is the case, but it will be left to the user to handle edge cases that would result in an invalid URL by using a filter. This point will be made clear in the documentation.

**Comment by esoergel** [comment]
Seems reasonable.  Would this be separate from a base URL?  Ie, you'd see two fields:
```
base_url: https://example.com/api/v3.1/
configurable_portion: "/{case_id}?param1="{param_1}"
```
That seems desirable so we have better assurances about what servers our system is submitting to (so we don't become a DDOS intermediary, for example).

Did you consider splitting out URL components and GET parameters?  The rules around them are a little different - we may need to escape characters, for example.  And would this support list types?  Like if a project needs to encode `?patient_type=pediatric&patient_type=oncology` or something.  I don't think we could reasonably support all ways servers choose to encode their data without providing a scripting language, so it's certainly fine to draw the line somewhere.

**Comment by proteusvacuum** [comment]
Yes, this would be separate from the base_url, and this extra part

> would be appended to the base url defined in the connection settings

I did consider splitting the URL components and the GET parameters, but I think having it like this makes it slightly more flexible. For lists, you could use a reduce items expression with a "join" https://commcare-hq.readthedocs.io/ucr.html#reduce-items-expression
You could technically use a reduce for the full custom part of the URL, but I think using a template is potentially a better UX.
