### ISSUE TITLE
[CEP] Do not preindex_everything on every deploy

### ISSUE THREAD

**Issue by millerdev** [dimagi/commcare-hq#32510]
### Abstract

This is a proposal to modify the deployment automation so it no longer calls `preindex_everything` automatically on every deploy. Instead, (p)reindex operations will be triggered on an as-needed basis by Django migrations. Automatic labels applied to pull requests will alert developers when a migration is required.

### Motivation

Currently the "preindex everything" step of the HQ deploy is orchestrated with various logical components, some of which are implemented in a management command in CommCare HQ, and some of which are implemented with Fabric in commcare-cloud. Relevant parts of the process include:

* The management command is run exactly once (on a single machine) per deploy. This is accomplished with a <code>[@run_once](https://github.com/dimagi/commcare-cloud/blob/7807f0fe8eef39b76f0b8c6b996b6e21a501387e/src/commcare_cloud/fab/operations/db.py#L15)</code> decorator on the fabric task. The "run once" behavior is not immediately obvious in the code since the task is also decorated with <code>[@roles(ROLES_PILLOWTOP)](https://github.com/dimagi/commcare-cloud/blob/7807f0fe8eef39b76f0b8c6b996b6e21a501387e/src/commcare_cloud/fab/operations/db.py#L14)</code>, which normally means that the task runs on every machine in the <em>pillowtop</em> group.
* The [`preindex_everything`](https://github.com/dimagi/commcare-hq/blob/7d5fc442ed6df03fb82e093843c9c7da858ee9d2/corehq/apps/hqadmin/management/commands/preindex_everything.py) management command is potentially a long-running process. <code>[at](https://linux.die.net/man/1/at)</code> is used to run the command in the background after a short delay, allowing the deploy to continue with other tasks while it completes (although as of this writing the logic that waits for completion happens immediately after the background task is initiated—reason unclear).
* Our custom resume deploy mechanism is critical for run-once-per-deploy behavior. If a preindex takes longer than 5 minutes the deploy will fail. Resuming the deploy later will skip the steps up to and including the one that starts the preindex, and begin with the step that checks if it is complete. Caveat: see [**Note 1**](#note1) below.
* The management command is run in a polling loop with <code>--check</code> to determine if the long-running background process has completed successfully, after which the deploy is allowed to proceed with other tasks.
* Finally, later after the preindex has completed, [`sync_finish_couchdb_hq`](https://github.com/dimagi/commcare-hq/blob/7d5fc442ed6df03fb82e093843c9c7da858ee9d2/corehq/preindex/management/commands/sync_finish_couchdb_hq.py) is called to rename the "preindexed" view documents to their non-temporary names during the _migrate_ step of the deploy.

Some parts of this process are not easily ported to Ansible in the process of removing Fabric from commcare-cloud. Specifically, Ansible assumes that all tasks are idempotent, and therefore resuming a previously started deploy requires some knowledge of previous deploy invocations to prevent a new deploy from running a new instance of the long-running `preindex_everything` command.

<a id="note1" />**Note 1**: there is nothing to prevent multiple instances of the preindex command from being run concurrently. For example, this could happen if a deploy fails and then another deploy is invoked (not using _resume_) while the preindex of the failed deploy is still in progress. The effect of running multiple concurrent preindex commands is unclear, and would appear to have a non-deterministic outcome.

**Note 2**: the names used for Couch views during the preindex process are not unique to the version of the view being preindexed. (They are named with the normal view name plus a `-tmp` suffix.) Running multiple concurrent preindex processes with different versions of the code would seem to have a non-deterministic outcome. Presumably this has never been a concern, but it does beg the question of why temporary view names are necessary if concurrent runs are not a concern?

**Note 3**: because of the way new versions of Couch views are created and reindexed, it appears that all changes must be backward-compatible or risk having previously deployed code interact with and possibly break on account of incompatible view state between when the preindex process is initiated and when new (compatible) code is deployed.

### Specification - to be implemented

* Add a new Django migration operation type to facilitate Couch view reindexing.
* @joxl has recently developed [migration operations for ElasticSearch](https://github.com/dimagi/commcare-hq/pull/32460). Very little attention has been given to the ElasticSearch portion of `preindex_everything` since its removal has been planned previously as part of the ElasticSearch upgrade, which is separate from this CEP.
* Update the [documentation of the "reindex/migration" tag](https://github.com/dimagi/commcare-hq/blob/master/CONTRIBUTING.rst#reindex--migration) to include the new requirement of adding a Django migration to perform the reindex since it will no longer be done automatically. Pull request authors will be alerted that a _reindex migration_ is required when the tag is automatically added to a PR as a result of the PR changing or adding a Couch design doc or ElasticSearch mapping.
  
  Long-running reindex migrations should be handled the same way that other long-running Django migrations are handled, and should be accompanied by change log entries if they are expected to disrupt the normal deploy cycle. Since all Couch reindex operations must already be backward-compatible or risk breaking running code, this imposes no new requirements for backward-compatibility.
* Remove deploy steps that call `preindex_everything`.

### Impact on users

None.

### Impact on hosting

New types of migration operations will be done using the already-established Django migration pattern. Unexpected long-running deploys should occur less frequently because more types of long-running operations will be accompanied by change log entries that direct affected environments to schedule pre-deploy maintenance as needed.

### Backwards compatibility

Changes to Couch design docs and ElasticSearch mappings will no longer be automatically reindexed on deploy. Those operations must be performed as part of a Django migration, which will need to be created as part of the PR that is making the change.

**Comment by snopoke** [comment]
Thanks for this @millerdev. This seems fine to me and aligns with our general 'maintenance operations' process.

As a side question, do you know how the existing process handles couch views that haven't changed? Do we just always have 'tmp' views around?

**Comment by snopoke** [comment]
> > how the existing process handles couch views that haven't changed?
> 
> `preindex_everything` [creates a new `tmp` version of each design doc](https://github.com/dimagi/commcare-hq/blob/9bb2e466ea790d4f23982f06c18aaa85baecf49c/corehq/ex-submodules/dimagi/utils/couch/sync_docs.py#L27) every time it is run. As far as I can tell this applies to all design docs, including ones that have not changed.
> 
> > Do we just always have 'tmp' views around?
> 
> Not exactly. The [`tmp` docs are copied over the non-`tmp` version](https://github.com/dimagi/commcare-hq/blob/9bb2e466ea790d4f23982f06c18aaa85baecf49c/corehq/ex-submodules/dimagi/utils/couch/sync_docs.py#L58) and then [the `tmp` version is deleted](https://github.com/dimagi/commcare-hq/blob/9bb2e466ea790d4f23982f06c18aaa85baecf49c/corehq/ex-submodules/dimagi/utils/couch/sync_docs.py#L60) during the ["migrate" phase](https://github.com/dimagi/commcare-cloud/blob/7807f0fe8eef39b76f0b8c6b996b6e21a501387e/src/commcare_cloud/fab/operations/db.py#L78) of the deploy.

That was also my read of the code but I don't understand how we could rebuild all the views on every deploy.

**Comment by millerdev** [comment]
> I don't understand how we could rebuild all the views on every deploy.

I agree. I think Couch must be doing some internal view checks to see if there is any new work to do.

**Comment by dannyroberts** [comment]
> > I don't understand how we could rebuild all the views on every deploy.
> 
> I agree. I think Couch must be doing some internal view checks to see if there is any new work to do.

That's right. Design doc names are essentially aliases to the underlying data, which are stored in a file named by some kind of hash of the view code. So if you have two design docs that are the same except for their name, they will alias the same underlying storage; this prevents it from rebuilding the entire index. Similarly if you delete a design doc (but don't trigger view cleanup) and then recreate exactly the same design doc, it'll find the data files right where it left htem.

**Comment by snopoke** [comment]
> > > I don't understand how we could rebuild all the views on every deploy.
> > 
> > 
> > I agree. I think Couch must be doing some internal view checks to see if there is any new work to do.
> 
> That's right. Design doc names are essentially aliases to the underlying data, which are stored in a file named by some kind of hash of the view code. So if you have two design docs that are the same except for their name, they will alias the same underlying storage; this prevents it from rebuilding the entire index. Similarly if you delete a design doc (but don't trigger view cleanup) and then recreate exactly the same design doc, it'll find the data files right where it left them.

Thanks for the explanation @dannyroberts, that makes sense. I had thought there was something like this happening but I thought it was on the client side (which does also do a hash check before pushing design docs).

**Comment by millerdev** [comment]
Implemented in
- https://github.com/dimagi/commcare-hq/pull/32544
- https://github.com/dimagi/commcare-cloud/pull/5748
