### ISSUE TITLE
Improve accuracy of Application Version report

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcare-hq#3345]
http://manage.dimagi.com/default.asp?111552

We look in a bunch of different places to check what the app version of the last submitted form was (see: https://github.com/dimagi/commcare-hq/blob/e068c3d1cf5fc7fc64451ad9e24513ddcd9ac116/corehq/apps/receiverwrapper/util.py#L47-47).

This function should be improved in a couple places:
- There's a new place to check as of https://github.com/dimagi/commcare-hq/pull/3278, which is the form's `build_id`. If you look that up in couch and it has a `version` property, then you've found the definitive answer. Otherwise you'll have to keep using the other techniques.
- Add more patterns to be checked, from the following example:
  - `CommCare ODK, version "2.11.0"(29272). App v65. CommCare Version 2.11. Build 29272, built on: February-14-2014` => `65`

**Comment by czue** [comment]
@dannyroberts is this still relevant?

**Comment by dannyroberts** [comment]
Almost certainly not yeah
