### ISSUE TITLE
UI Translations selecting suggestion doesn't change underlying value

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcare-hq#3356]
http://manage.dimagi.com/default.asp?111682

To reproduce:
1. Make a new app and add a language other than english (try fra).
2. Add some arbitrary translations (can be 'foo', 'bar') and save.
3. Make a new app and add the same language. Add a 'foo', but leave the translation blank. Save.
4. Now click on the blank translation box, and you should get a drop down that just has 'bar' in it.
5. Select 'bar', and notice that the save button doesn't change.
6. Make some other change (like adding another translation), and save. Reload and notice that 'bar' didn't get saved even though it appeared in the box in the UI before you hit save.

This is indicative of a UI element not actually changing the underlying value of the text box and/or not triggering a 'change' event.

The code for this is here: [corehq/apps/translations/static/translations/js/translations.js](https://github.com/dimagi/commcare-hq/blob/921c36d6925c38732bf6d126a325db13d0483a6b/corehq/apps/translations/static/translations/js/translations.js#L58-58)

**Comment by czue** [comment]
This is fixed (approximately 6 and a half years ago).
