### ISSUE TITLE
Please update the development contribution readme = How to setup project locally

### ISSUE THREAD

**Issue by LOVKUSH9888** [dimagi/commcare-hq#33944]
**Abstract**
How to set up a project locally

**Motivation**
wanted to get more info on setting up a project locally

**Specification**
Dev local setup detail in the readme. md

**Comment by millerdev** [comment]
Hi @LOVKUSH9888, are you are setting up for local development? See [the dev setup guide](https://github.com/dimagi/commcare-hq/blob/master/DEV_SETUP.md).

Otherwise have a look at the [CommCare HQ Deployment documentation](https://commcare-cloud.readthedocs.io/en/latest/).

**Comment by LOVKUSH9888** [comment]
Thanks will do.
