### ISSUE TITLE
Enable Uploading of images in CloudCare

### ISSUE THREAD

**Issue by jjackson** [dimagi/commcare-hq#4162]
Request:  

"Is anyone working on uploading images in CloudCare? My organization requires the ability to upload images from an internet connected computer. We're testing android emulators bluestacks and youwave, but it would be much easier to have this functionality in CloudCare."

Recommended Approach:

CloudCare forms are rendered by a "touchforms" daemon process. This is essentially the standard JavaRosa CommCare core wrapped in Jython. You can see the github repository here: https://github.com/dimagi/touchforms

One method you might want to look at to get started is this one (renderQuestions):
https://github.com/dimagi/touchforms/blob/1f31c4f7e0940f290c0c5639791090b820f608fc/touchforms/formplayer/static/formplayer/script/entrycontrols_full.js#L764

You'll need to create a new control type for the image upload question. Take a look at the FreeTextEntry for an example:
https://github.com/dimagi/touchforms/blob/1f31c4f7e0940f290c0c5639791090b820f608fc/touchforms/formplayer/static/formplayer/script/entrycontrols_full.js#L131

**Comment by czue** [comment]
This may still be a good feature, but the technical details are no longer relevant and this doesn't seem like a good place to track it regardless. @snopoke think we can close it?
