### ISSUE TITLE
downloading app error

### ISSUE THREAD

**Issue by omiltoro** [dimagi/commcare-hq#5417]
Hi Everyone,

I am not able to download the artifacts from teamcity kindly assist.

I am getting the following error.

Unexpected Error

This was not supposed to happen. Please provide the error details to your TeamCity server maintainer.
If you maintain this TeamCity installation please report this error to JetBrains.

Error message: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.ServletException: java.lang.ClassFormatError: Truncated class file

**Comment by czue** [comment]
There is a new build server where you should download artifacts from. @wpride can point you where you can find that.

**Comment by omiltoro** [comment]
Thank you @czue . That was prompt. It would be prudent to update the documentations too.

**Comment by czue** [comment]
yep, we're in the process of finishing moving everything over, but will definitely update documentation as soon as it's finished.

**Comment by omiltoro** [comment]
@wpride kindly assist at your earliest convinience

**Comment by omiltoro** [comment]
@czue is @wpride  reachable?

**Comment by czue** [comment]
he's on the east coast of the US so probably will be online in the next couple hours.

**Comment by wpride** [comment]
@omiltoro please refer here http://jenkins.dimagi.com/view/CommCare%20Mobile/ to find the authoritative artifacts from here on

**Comment by omiltoro** [comment]
Thanks very much @wpride

**Comment by omiltoro** [comment]
@czue i managed to add the app builds to commcarehq as follows

(commcare-hq)patrick@patrick-PowerEdge-T100:~/Downloads/commcare-hq$ python manage.py add_commcare_build /home/patrick/Downloads/archive/app/dist/commcare-odk.apk 2.0.0 352782
2015-02-04 07:01:46,275 INFO Raven is not configured (disabled). Please see documentation for more information.
Build 2.0.0 #352782 created
You can see a list of builds at [your-server]/builds/
(commcare-hq)patrick@patrick-PowerEdge-T100:~/Downloads/commcare-hq$

However I'm not able to deploy the app  with the following message

ResourceNotFound: Document is missing attachment
[04/Feb/2015 06:59:20] "POST /a/cafarmerscops/apps/save/655286222b0a55969509066c22b4c9d6/ HTTP/1.1" 500 51354

**Comment by czue** [comment]
@omiltoro can you provide a complete stack trace?

**Comment by omiltoro** [comment]
@czue link to pastebin http://pastebin.com/xAygpCqu

**Comment by czue** [comment]
It does look like the file wasn't uploaded properly (or perhaps there's some other error going on). @dimagi/team-commcare-hq and @wpride might have to look closer to come up with a solution.

**Comment by omiltoro** [comment]
@czue do we load the apps when the virtual environment is active?

**Comment by dannyroberts** [comment]
@omiltoro I don't understand your last question. If you navigate to <your instance>/builds/edit_menu/, make sure you've added your newly uploaded version to that list, which represents the versions available to choose from when you build an app.
- if you version isn't available in the dropdown at /builds/edit_menu/, then follow the instructions at the bottom to add it

Then navigate to your application and make sure that your new version is selected as the CommCare Version (under General Settings, on the app's settings page).

Let me know whether you are still seeing the same stack trace after you've confirmed all of these steps.

**Comment by wpride** [comment]
@omiltoro please see updated documentation. Sorry for the inconvenience.

**Comment by omiltoro** [comment]
thank you all. Could someone help with a simple short webcast on building apps. @czue @wpride @dannyroberts  it would really help

**Comment by dannyroberts** [comment]
@omiltoro Thanks for your suggestion. Passing on to @amsagoff. Glad we could help you work through the issue you were experiencing!

**Comment by omiltoro** [comment]
Im still waiting for the link @amsagoff

**Comment by omiltoro** [comment]
@dannyroberts  im still getting the error

**Comment by wpride** [comment]
@omiltoro have you cleared out the old builds? You will need to delete any builds with the old (unsupported) .zip structure from your couch DB

**Comment by omiltoro** [comment]
@wpride  i did a re-installation of commcare and now still receiving the same error may be a small video could really save me .

**Comment by wpride** [comment]
@omiltoro Can you confirm that you cleared the old builds out of couchdb?

**Comment by omiltoro** [comment]
@wpride i did a fresh installation on another pc.

On Thu, Feb 12, 2015 at 6:11 PM, wpride <notifications@github.com> wrote:

> @omiltoro <https://github.com/omiltoro> Can you confirm that you cleared
> the old builds out of couchdb?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/issues/5417#issuecomment-74086326>.
>



-- 






Systems Developer/Programmer
Snapshot Cv:http://kinzaa.com/omiltoro
Github:www.github.com/omiltoro
Mobile : 0722142396
+254722142

Keep it SMART

We can not do great things. We can only do little things with great love. --
Mother Teresa
<http://www.quotemountain.com/fullsearch.php?searchtxt=Mother+Teresa&matching=3>
Call
Send SMS
Add to Skype
You'll need Skype CreditFree via Skype

**Comment by omiltoro** [comment]
could someone assist please @wpride

**Comment by NoahCarnahan** [comment]
##### Step 1, Clear out old builds
- Start couch db if it's not already running.
- Navigate to `http://127.0.0.1:5984/_utils/database.html?commcarehq/_design/builds/_view/all` in a web browser. You will need to change the `127.0.0.1:5984` part of the url if couch db is running at a different location.
- You should now see a list of documents in the database. You want to delete all of the documents who's "key" starts with "2.19" (for example, the last two rows in the attached screenshot). Delete rows by clicking on the row, then clicking the "Delete Document…" button that will apear on the document's page. (Don't ever click "Delete Database…", which appears in the same spot on some other pages).

##### Step 2, Re-upload the build
- Make sure HQ is running on your machine.
- Navigate to `http://192.168.1.14:8000/builds/edit_menu/`. You will probably have to adjust the `192.168.1.14:8000` to match the address and port that you are running the server on.
- In the form at the bottom of the page enter the following information:
    - Source for artifacts.zip: `http://jenkins.dimagi.com/view/CommCare%20Mobile/job/commcare-mobile-2.19/346003/artifact/application/posttmp/artifacts.zip`
    - Version: `2.19.0`
    - build number: `346003`
- Click the "Import build" button. This might take a moment to process.
- Then, add a 2.19.0 item to the "Menu Options" list at the top of the `builds/edit_menu/` page. Click the "Submit" button once you've added it to the list.

I think this is all the steps. Let me know if you run into any problems.

![screen shot 2015-02-19 at 11 48 05 am](https://cloud.githubusercontent.com/assets/2117127/6264687/ab2db3ba-b82e-11e4-846e-40327055a85e.png)

**Comment by omiltoro** [comment]
thanks @NoahCarnahan  i will try your approach and see

**Comment by omiltoro** [comment]
@NoahCarnahan  when i navigate to  myserver:8000/builds/edit_menu/

I receive a 403 error i do not have permission

[19/Feb/2015 11:05:54] "GET /no_permissions/?next=/builds/edit_menu/ HTTP/1.1" 403 14572

**Comment by NoahCarnahan** [comment]
@omiltoro, are you signed in? If you are and you continue to get that error you will need to make your account a superuser account.
You can do that on the command line where you launch hq from. Run the command
```
python manage.py createsuperuser
```
That will run you through an interactive prompt for setting the username and password and such.

**Comment by omiltoro** [comment]
@NoahCarnahan  was able to add the build successfully  but im still receiving this error
KeyError: "Can't find build 2.0.0/latest. For instructions on how to add it, see https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/builds/README.md"

**Comment by omiltoro** [comment]
Hi @czue @NoahCarnahan  i managed to build an app had to delete the old builds and recreate a new app in commcare.

**Comment by czue** [comment]
glad to hear it!

**Comment by omiltoro** [comment]
@czue i believe someone must have reported this issue im facing at the moment. I am not able to sync forms to the commcarehq 

 ERROR Status code 400 for a form submission. Response is: 
Content-Type: text/html; charset=utf-8

If you use multipart/form-data, please name your file xml_submission_file.
You may also do a normal (non-multipart) post with the xml submission as the request body instead.

**Comment by czue** [comment]
@omiltoro - in order to submit from a phone you need to use a proxy server configured to support chunked encoding. There are sample nginx and apache config files you can start from in the repository.

**Comment by omiltoro** [comment]
@czue  @dannyroberts is this the link to the config files  https://github.com/dimagi/commcare-hq/blob/master/deployment/apache/local_apache.conf

Another question? How do i add these to my setup. Ive tried editing the apache2 config file and nothing seems to change. Could some one guide?

**Comment by NoahCarnahan** [comment]
@omiltoro , you need to place that file in a special location on your computer, and then start apache with a command like `apachectl start` or `apachectl restart`
I'm not sure if windows usually comes preinstalled with Apache, in which case you should probably follow the directions here: http://httpd.apache.org/docs/2.4/platform/windows.html . It looks like that page also talks about `.conf` files and where they should be located, so once you determine if Apache is installed or not, you can start looking at the existing `.conf` files.

On my machine, there is an apache configuration file at `/etc/apache2/httpd.conf`. The last line of that file reads: `Include /private/etc/apache2/other/*.conf`, which means "include all of the configurations specified in files in the `/private/etc/apache2/other/` directory that end with `.conf`. So, when I set up my environment I placed a copy of [the file you linked](https://github.com/dimagi/commcare-hq/blob/master/deployment/apache/local_apache.conf) at ` /private/etc/apache2/other/cchq.conf`.
Note though that your paths will be different because you are using a different operating system.
I believe Clayton is on a Windows machine, so he may be able to help with Windows specific questions.

**Comment by omiltoro** [comment]
@NoahCarnahan thanks im setting up on ubuntu 12.0.4

**Comment by NoahCarnahan** [comment]
Ah ok, that will make it easier. I'm on OSX, but I imagine a google search
for "ubuntu apache conf" will turn up some good clues as to where to put
the configuration file.

**Comment by omiltoro** [comment]
it seems my httpd.conf file is blank @NoahCarnahan

**Comment by omiltoro** [comment]
@NoahCarnahan  @czue  i added the file to the conf.d directory as directed by this site http://www.control-escape.com/web/configuring-apache2-debian.html but still getting the errors

**Comment by snopoke** [comment]
Hi Patrick

You should add the file to the the `/etc/apache2/sites-available` folder.
You can then run the command (assuming the file you copied is called
`cchq.conf`):
```
$ sudo a2dissite 000-default.conf
$ sudo a2ensite cchq.conf
```

This will disable the default apache config and enable your one.

You need to make sure your local commcare instance is running on port 8000
(which is the default django port) and you should also set the
`BASE_ADDRESS` setting in your `localsettings.py` file to be equal to your
machine's IP address e.g. `BASE_ADDRESS = '192.168.0.4'`

Having done that you'll need to make a new build of your app so that it
points to the correct URL's (using the correct base address). You should
then be able to install the app to your phone and submit data.

On 2 March 2015 at 12:50, Patrick <notifications@github.com> wrote:

> @NoahCarnahan <https://github.com/NoahCarnahan> @czue
> <https://github.com/czue> i added the file to the conf.d directory as
> directed by this site
> http://www.control-escape.com/web/configuring-apache2-debian.html but
> still getting the errors
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/issues/5417#issuecomment-76691658>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by omiltoro** [comment]
@snopoke  your method does not work for me

**Comment by snopoke** [comment]
Perhaps we should move this from the PR to the commcare-developers group: https://groups.google.com/forum/#!forum/commcare-developers

**Comment by omiltoro** [comment]
@wpride @czue ideas ?
