### ISSUE TITLE
Create J2ME jar/jad pair lazily

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcare-hq#8422]
## Motivation

- Very few builds percentage-wise are intended for J2ME
- J2ME requires an extra build step per "Make New Version" of your app
- This extra step requires making a system call to a java program (rather expensive), and then posting a rather larger attachment to the couch document representing the build
- For most builds, we could skip this entirely
- For J2ME builds, we could do this on-demand, when someone first requests that resource, from the same files already generated for the build

## Steps
- First, verify that that's true: other than just taking the pre-made files (the ones used for ODK) and unzipping the J2ME jar, adding the files, rezipping & signing.
- If there are other files that we don't generate separately, we want to generate them on build too.
- Move the J2ME jar code from the main build process to its own function
- Call that function from the URL hit when you ask to download the jad or jar files.
- Tricky / annoying: people usually download the jad and jar files one right after the other, and you don't want both of these things to trigger the loading. You may want to have them use a redis lock to make sure only one of them goes for it, and the other then uses the work from the first one.

**Comment by czue** [comment]
:+1:

**Comment by snopoke** [comment]
nice

**Comment by emord** [comment]
Think this was fixed https://github.com/dimagi/commcare-hq/pull/10230
