### ISSUE TITLE
Problems with setting up Elasticsearch

### ISSUE THREAD

**Issue by philipkaare** [dimagi/commcare-hq#9941]
I have set up CommcareHQ to run inside docker. 

When I try to create mobile users i get the following error: 

See: http://pastebin.com/t5sgURtL

It seems to be related to elasticsearch not being set up correctly. I have initialized CommcareHQ with the following docker commands: 

docker run --rm --link postgres:postgres --link elasticsearch:elasticsearch --link couchdb:couchdb --link redis:redis commcare-hq python manage.py sync_couch_views
docker run --rm --link postgres:postgres --link elasticsearch:elasticsearch --link couchdb:couchdb --link redis:redis commcare-hq env CCHQ_IS_FRESH_INSTALL=1 python manage.py migrate --noinput
docker run --rm --link postgres:postgres --link elasticsearch:elasticsearch --link couchdb:couchdb --link redis:redis commcare-hq python manage.py collectstatic --noinput
docker run --rm --link postgres:postgres --link elasticsearch:elasticsearch --link couchdb:couchdb --link redis:redis commcare-hq python manage.py compilejsi18n
docker run --rm --link postgres:postgres --link elasticsearch:elasticsearch --link couchdb:couchdb --link redis:redis commcare-hq python manage.py bootstrap example example@example.com example
docker run --rm --link postgres:postgres --link elasticsearch:elasticsearch --link couchdb:couchdb --link redis:redis commcare-hq python manage.py run_ptop --all
docker run --rm --link postgres:postgres --link elasticsearch:elasticsearch --link couchdb:couchdb --link redis:redis commcare-hq python manage.py ptop_es_manage --flip_all_aliases

And to run: 

sudo service apache2 start
python manage.py run_ptop --all
env C_FORCE_ROOT=1 python manage.py celeryd --verbosity=2 --beat --statedb=celery.db --events
python manage.py compilejsi18n
python manage.py runserver 0.0.0.0:8000

I really hope someone can help :)

**Comment by benrudolph** [comment]
Hi @philipkaare what version of elasticsearch are you using?

**Comment by philipkaare** [comment]
The newest one which docker pulls down. I was a bit confused which version to use. The dockerfile provided in the standard repository just uses the most recent one. 
Should I downgrade to 0.90.13?

**Comment by philipkaare** [comment]
Thanks for the super fast reply!

**Comment by benrudolph** [comment]
we're in the process of upgrading ES. you should be fine with 1.7, but we have no data on 2.x

**Comment by philipkaare** [comment]
Okay, are the commands above enough to get it running?

**Comment by philipkaare** [comment]
Is there a specific version you recommend?

**Comment by benrudolph** [comment]
i'd recommend 1.7. those commands above should do it. though admittedly haven't tested docker too much so not sure how that factors in

**Comment by philipkaare** [comment]
Okay, I am trying to get a running installation with Docker. We plan to use it in Guinea-Bissau where internet access is very patchy, so we need to run it on our own server. I have forked it at: https://github.com/philipkaare/commcare-hq if this has any interest for you guys - I think my Dockerfile and docker-run.sh are a fairly close to working with your most recent master branch. 

I am trying now with 1.7.4 and then we'll see. Thanks again for replying quickly :)

**Comment by benrudolph** [comment]
no problem, let me know how it goes. good to hear; will check out the docker file. has been on our list of things to do

**Comment by czue** [comment]
@philipkaare you might also want to check out our ansible repository if you're interested in setting up a production rig: https://github.com/dimagi/commcarehq-ansible. It can be a better way to get setup for deployment than the readme.

as an aside - dimagi also does paid managed local hosting for folks.  if that's of any interest to you/your team i can put you in touch with someone on our side who could chat further with you.

**Comment by philipkaare** [comment]
I'll drop you a line when I think I have something finished. I may be asking for a bit more help in the days to come - hope you don't mind. 

Thank you @czue , I would like to hear about the options for some kind of paid assistance. I think we will try to get as much up and running by ourselves as we can, but we might be interested in some assistance. I'll take a look at the ansible repository, I had not noticed that was available. Right now it seems to be down to the last details as far as I can tell. 

And I can report that Elastic 1.7.4 seems to be working somewhat better - it now lists my mobile users :)

**Comment by czue** [comment]
nice! yeah if you've gotten that far i suspect you don't need us :)
